### ISSUE TITLE
Mekanism Compatibility

### ISSUE THREAD

**Issue by guicogo** [TheLMiffy1111/JAOPCA#10]
The Mekanism intermediary products are generating just fine, but none are able to be processed in the Mekanism machines, not even the ores.

**Comment by TheLMiffy1111** [comment]
1. Did you try putting them into the machines?
2. What Minecraft and Mekanism version?

**Comment by guicogo** [comment]
1. Yes, even though they don't show in JEI.
2. Minecraft 1.11.2 and Mekanism 9.3.2.307.

PS: I tried again, I think they aren't showing in JEI but they work fine. Sorry about this.
