### ISSUE TITLE
[Mod Compat] Embers Rekindled

### ISSUE THREAD

**Issue by Dragnier** [TheLMiffy1111/JAOPCA#103]
JAOPCA does not recognize two of the Embers Rekindled ores.... which is weird because it should since it uses the same modid as original Embers. I'm trying to get the two ores which do not usually have Native Clusters in Thaumcraft to have them; aluminum and nickel. No matter what I do, JAOPCA doesn't see those ores from Embers at all for any module.

**Comment by TheLMiffy1111** [comment]
DaedalusGame/EmbersRekindled/issues/146
