### ISSUE TITLE
Advanced Rocketry crash

### ISSUE THREAD

**Issue by kragnoth** [TheLMiffy1111/JAOPCA#107]
AdvancedRocketry-1.12.2-1.4.1-123-universal.jar released on 1/21 
and 
jaopca: JAOPCA-1.12.2-2.2.8.100.jar

libvulpes: LibVulpes-1.12.2-0.4.0-1-universal.jar

causes the following crash due to advanced rocketry changing how recipes are processed:

http://www.hatebin.com/eyqwbclwcg

**Comment by kragnoth** [comment]
It should be noted I get the following crash with just advanced rocketry:
https://hastebin.com/xiqudineca.sql

**Comment by TheLMiffy1111** [comment]
Has this been fixed on Advanced Rocketry's side?
