### ISSUE TITLE
Crash due to IC2 integration 

### ISSUE THREAD

**Issue by rinOfTheStars** [TheLMiffy1111/JAOPCA#11]
[crash-2017-07-16_16.18.00-client.txt](https://github.com/TheLMiffy1111/JAOPCA/files/1151331/crash-2017-07-16_16.18.00-client.txt)
is the crash report provided by the game. Seems to be an issue caused by the newest version of IC2 changing something?

**Comment by TheLMiffy1111** [comment]
Fixed
