### ISSUE TITLE
JAOPCA native clusters are not compatible with Thaumcraft Refinining enchantment

### ISSUE THREAD

**Issue by CommanderTvis** [TheLMiffy1111/JAOPCA#111]
JAOPCA adds Thaumcraft native clusters, but they are not obtainable with Refining enchantment... Is it possible to implement dropping native clusters of JAOPCA when an ore block is broken with tool, enchanted with Refining?

**Comment by TheLMiffy1111** [comment]
JAOPCA already does this.
