### ISSUE TITLE
RFTools Builder Problem

### ISSUE THREAD

**Issue by meurotops** [TheLMiffy1111/JAOPCA#113]
I've a problem with the RFTools Builder as quarry. It does not collect the xp orbs. So my server crashed... I killed all xp orbs via console.

**Comment by TheLMiffy1111** [comment]
wrong repo

**Comment by meurotops** [comment]
No that's wrong (maybe I wrote not enough)
I added the JAOPCA mod and after adding I get this problem, that the Builder is not able to collect all xp orbs. 
Before adding this works
My question is: can I disable the xp I get on all ores?
