### ISSUE TITLE
Additional embers support

### ISSUE THREAD

**Issue by RCXcrafter** [TheLMiffy1111/JAOPCA#115]
Recently the geologic separator has been added to embers which allows for secondary outputs from melting ores. There's also a gear stamp that's currently not supported and [soot](https://minecraft.curseforge.com/projects/soot) adds a nugget stamp.

Additionally it would be cool if all tinkers smeltery recipes were automatically added to the embers melter but that might not be in the scope of this mod.

**Comment by TheLMiffy1111** [comment]
Added
