### ISSUE TITLE
[Suggestion] Tiny pile to normal dust

### ISSUE THREAD

**Issue by TheRealWebGremlin** [TheLMiffy1111/JAOPCA#116]
The IC2 tiny pile of dusts from the Ore Washer can be made into normal dusts inside the Compressor. However, tiny piles added by JAOPCA (e.g. nickel, osmium), which are also obtained from the Ore Washer, do not go into the Compressor. The only way to turn JAOPCA's tiny piles into normal dusts is via 3x3 crafting or the tinker's smeltery.

I think it would make automation easier, and fit the theme, if JAOPCA's piles could be put into the Compressor as well. Rather than having a Compressor for the standard piles, and using autocrafters for JAOPCA's piles.

**Comment by TheLMiffy1111** [comment]
Added
