### ISSUE TITLE
[1.12] Does not work with event-based registered items

### ISSUE THREAD

**Issue by TheLimePixel** [TheLMiffy1111/JAOPCA#12]
To put it simply, the Cobalt and Ardite dusts don't show up in the 1.12 version with TIC installed.

**Comment by TheLMiffy1111** [comment]
Seems like I will have to start migrating to event-based registries.

**Comment by TheLMiffy1111** [comment]
Seems like many forgot the convention of doing OreDictionary right after blocks and items. Please also report this to TConstruct.

**Comment by TheLMiffy1111** [comment]
"Fixed" and added.
