### ISSUE TITLE
[1.12.2] Crash on Startup with newest Sky Compression

### ISSUE THREAD

**Issue by ToMe25** [TheLMiffy1111/JAOPCA#122]
JAOPCA causes a Crash on startup with the newest Sky Compression version due to the Package renaming in a prior update.

Mod Versions:
Forge Version: 14.23.5.1836,
Wrapup Version: 1.1.3,
JAOPCA Version: 2.2.8.101,
Sky Resources Version: 2.3.8,
Sky Compression Version: 1.2.2.5

Other Mods used:
CodeChickenLib 3.2.2.353

Crash Report: [crash-2019-05-06_12.50.20-client.txt](https://github.com/TheLMiffy1111/JAOPCA/files/3147579/crash-2019-05-06_12.50.20-client.txt)

**Comment by ToMe25** [comment]
BTW: Please look at the Pull Requests(and maybe Issues) on JAOPCAAgriculture and JAOPCASingularities.

**Comment by Mrbysco** [comment]
The happened because I renamed the package of Sky Compression to comply with Java package naming conventions meaning every mod that adds compat needs to change their calls from the old to the new  lowercase package.
