### ISSUE TITLE
[1.12] Draconium JEI Bug

### ISSUE THREAD

**Issue by TheLimePixel** [TheLMiffy1111/JAOPCA#13]
In the smeltery 3 Draconium Ingots = 144mb of Molten Draconium, as in 3 are smelted into 144mb and 144mb are casted into 3, instead of just one. This becomes an even bigger problem when the nuggets and blocks give the normal amount of Molten Draconium making it so that you can triple your Draconium Ingots if you smelt them as nuggets.

![image](https://user-images.githubusercontent.com/25333164/28675566-8f157a74-72e8-11e7-833b-853252a83a18.png)

**Comment by TheLimePixel** [comment]
Never mind, it's a JEI bug.

**Comment by TheLMiffy1111** [comment]
Maybe report this to Tinker's Construct or Draconic Evolution? I don't see anything here that causes this.

**Comment by TheLimePixel** [comment]
It's not really that big of a problem. This sometimes happens to other mods.
