### ISSUE TITLE
Embers Rekindled melter recipes don't seem to use melter amount specified in embers config

### ISSUE THREAD

**Issue by SeriousCreeper** [TheLMiffy1111/JAOPCA#135]
Heya,

i'm currently using this mod and embers rekindled (among others) to add support for some more ores. While this mod does add recipes to the melter (say betweenlands octine -> liquid octine), it always seems to use a value of 288mb per ore. In the embers config i have it set to 72 per ore (it gets multiplied by 2 by default, so i would get a total of 144). 

Would it be possible for JAOPCA to somehow use that config value for the added entries? 

Cheers,
SC

**Comment by TheLMiffy1111** [comment]
Should be fixed in 2.3.0.0
