### ISSUE TITLE
Configuration option to disable all recipes registered by the mod.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TheLMiffy1111/JAOPCA#139]
I'm making a custom modpack, and while yes, on it's own JAOPCA works wonders, however for pack making it's a pain that it adds custom recipes for items, I could remove crafting table recipes manually, and even some modded "machines" too, however some mods like IC2 don't allow this, I can set the IC2 config files to have no recipes in them for the macerator for example, however JAOPCA's recipes cannot be removed this way as they're not actually part of that config file.
The only means of removing these recipes I can think of is overwriting them with new ones that use the same input, but that defeats the purpose entirely.

**Comment by vizthex123** [comment]
There's options to disable modules in the config, but it seems like they get ignored. Very irritating.

**Comment by TheLMiffy1111** [comment]
Added in 2.3.0.0
