### ISSUE TITLE
Difficulty with liquids

### ISSUE THREAD

**Issue by wizard1399** [TheLMiffy1111/JAOPCA#14]
I am having trouble using your liquids in craft tweaker scripts. I am trying to add a recipe to embers melter that puts the dust from your mod generates and melts it into the liquid form. The liquid shows up in JEI but does not have a name (ex: jaopca:liquidLapis) that craft tweaker can make use of. Can you take a look into this?

Using .17 vers on mc 1.10.2

**Comment by TheLMiffy1111** [comment]
The name should be jaopca:\<material name\>

**Comment by wizard1399** [comment]
I think some part of your fluids is not correctly registered. When I bring them up in JEI, there is no name space listed. I also can not give myself the fluid so I can place it in world.

**Comment by TheLMiffy1111** [comment]
I currently do not know how to make my fluids placeable. Also I think JEI doesn't show fluid names of block-less liquids.
The name should be simply \<material name\> following TCon's names.

**Comment by wizard1399** [comment]
So I figured out it that I was trying to use the wrong thing. I got most of it working now, but I am still having trouble getting "molten refined coralium" liquid from abyssalcraft to work with the embers melter. I noticed that the dust is called liqifiedcoralium. Is there something I am missing here?

 This would be so much easier if there was a command that would dump the liquid registery.

**Comment by TheLMiffy1111** [comment]
That fluid is called "liqified_coralium".

**Comment by wizard1399** [comment]
Thanks for the help. Would you like a copy of the craft tweaker script oncevi get everything worked out to ise as an example?

**Comment by TheLMiffy1111** [comment]
Closed as this seems to have been resolved, and fluid blocks have been added.
