### ISSUE TITLE
[1.14.4, 3.0.0.11] Crash on startup

### ISSUE THREAD

**Issue by Peca21** [TheLMiffy1111/JAOPCA#140]
I just downloaded ATM 4 modpack and the game crashed during "constructing mods".

[Pastebin link](https://pastebin.com/YA2CzWYQ)

https://github.com/AllTheMods/ATM-4/issues/73

**Comment by TheLMiffy1111** [comment]
Can you check if it still crashes?

**Comment by Peca21** [comment]
I downloaded new modpack version 0.3.0, which has new JAOPCA version 3.0.0.12 and it's not crashing anymore.

Note; I launched the modpack using GDLaucnher
