### ISSUE TITLE
[Request] Add compatibility for Omegacraft and C.O.M.B.A.T.

### ISSUE THREAD

**Issue by RZiegler979** [TheLMiffy1111/JAOPCA#143]
Title, I love the concept and past functionality of this mod. However, with 1.15.2 different mods are taking the lead in the tech and ore adding fields. Right now with Mekanism, Combat, and omega I have 3 different copper ores. Ugh. Would love to see the other two added to your list for 1.15.2.

**Comment by TheLMiffy1111** [comment]
Not the aim of this mod
