### ISSUE TITLE
1.15.2[forge-JAOPCA} incompatible after flux updating

### ISSUE THREAD

**Issue by SDUBZ** [TheLMiffy1111/JAOPCA#147]
JAOPCA-1.15.2-3.0.0.19
fl-3.0.9
flux-4.8.4
Forge-1.15.2-31.1.16
logs:
[latest.log](https://github.com/TheLMiffy1111/JAOPCA/files/4271171/latest.log)

![ScreenShot_20200301113034](https://user-images.githubusercontent.com/14084377/75617214-2ae14700-5bb0-11ea-9c27-4835d2cb74c9.png)

**Comment by TheLMiffy1111** [comment]
Fixed in new version
