### ISSUE TITLE
1.15.2 - Crash with Mekanism 404+

### ISSUE THREAD

**Issue by Partonetrain** [TheLMiffy1111/JAOPCA#148]
I'm guessing Mekanism got a refactor and JAOPCA doesn't know where things are anymore.

Forge 31.1.18
Mekanism 1.15.2-9.9.14.406
JAOPCA 1.15.2-3.0.0.20

~~Log: https://pastebin.com/44MY9RG6~~
~~Stacktrace included CobbleForDays, new log with same error without CFD:
https://pastebin.com/6efuVPdG~~

Log, but this time with ONLY Mekanism and JAOPCA: (should've done this in the first place)
https://pastebin.com/p5ZciybT

**Comment by SDUBZ** [comment]
getting same crash
same crash with forge: 31.1.16
logs:
[latest.log](https://github.com/TheLMiffy1111/JAOPCA/files/4290831/latest.log)

**Comment by TheLMiffy1111** [comment]
Fixed in 3.0.0.21
