### ISSUE TITLE
[1.14.4] Create Compatibility

### ISSUE THREAD

**Issue by NielsPilgaard** [TheLMiffy1111/JAOPCA#151]
A recent major update to the mod [Create](https://www.curseforge.com/minecraft/mc-mods/create) added a new ore processing system, where ores are crushed into crushed versions of said ore. The special thing is, the crushed output can be "washed" to produce 10 nuggets and 50% chance of another 5. 

I would like JAOPCA to add Crushed versions of the materials you support, so Create's unique ore processing can be used for everything in any given modpack.

I hope you'll consider it, thanks for reading.

### Screenshots
![billede](https://user-images.githubusercontent.com/21295394/79077147-864e3b00-7cff-11ea-8ac9-5f5fbafe8932.png)
![billede](https://user-images.githubusercontent.com/21295394/79077149-89e1c200-7cff-11ea-9f0a-e8389089a527.png)

**Comment by TheLMiffy1111** [comment]
Added

**Comment by NielsPilgaard** [comment]
Thank you :)
