### ISSUE TITLE
[1.15.2] Weird incompatibility with SilentGems + Mekanism 411

### ISSUE THREAD

**Issue by Ouack23** [TheLMiffy1111/JAOPCA#152]
Java is version 1.8.0_241, using 64-bit architecture.

--fml.forgeVersion 31.1.44

Mods:
  [✔️] JAOPCA-1.15.2-3.2.0.8
  [✔️] Mekanism-1.15.2-9.9.19.411
  [✔️] SilentGems-1.15.2-3.5.1+84
  [✔️] SilentLib-1.15.2-4.6.0+48

I got the following crash report :
https://pastebin.com/MZABm95d

Full log :
https://pastebin.com/JUp7GYwr

If I remove any of the above mods, the game launches correctly. It seems that it is not a Mekanism issue ( https://github.com/mekanism/Mekanism/issues/6056 )

Edit : Crash with Mekanism 412 too. Crashlog mentions JAOPCA.
https://pastebin.com/Rg8hnw56

**Comment by Peca21** [comment]
I am getting the crash that looks the same in the last link.

**Comment by elowanut** [comment]
According to the Mekanism dev response to the Mekanism Issue I posted (which is the same error as this one), this relates to changes to the Mekanism Gas API. JAOPCA will have to update for compatibility. (see [Mekanism Issue #6063](https://github.com/mekanism/Mekanism/issues/6063))

**Comment by Boomflex** [comment]
Yes, same issue here: https://pastebin.com/4CpSPFKf

**Comment by TheLMiffy1111** [comment]
Fixed
