### ISSUE TITLE
[1.15.2/1.12.2] Adding all instead of replacing

### ISSUE THREAD

**Issue by TheUntamed** [TheLMiffy1111/JAOPCA#154]
Is it possible to enable the blocks, dusts, etc. for all materials even if there is a mod already adding the item for that material instead of just adding those that are missing?

**Comment by TheLMiffy1111** [comment]
No, but why would this be wanted?

**Comment by TheLMiffy1111** [comment]
Duplicate of #125

**Comment by TheUntamed** [comment]
Because then all blocks, items etc have the same type of texture.
Every mod adds it's own style of texture and I don't like inconsistency.
