### ISSUE TITLE
Question about Item/Block Textures

### ISSUE THREAD

**Issue by TheUntamed** [TheLMiffy1111/JAOPCA#155]
How did you create the textures? They have the colors of the different materials but the shades and shadows are the same for all textures. It doesn't look like they were all created manually and I would like to know how you created them.

**Comment by DabbingEevee** [comment]
it is just colorized white items

**Comment by TheUntamed** [comment]
I just don't understand how it is possible to create fancy textures this way. I tried it. I created a plane 16x16 texture of one color and placed the grayscale texture above it or made the plane one color texture transparent and placed the grayscale beneath it. The result was never fancy.

**Comment by TheLMiffy1111** [comment]
Maybe try looking at the model files and textures
I can’t really put it in words

**Comment by TheUntamed** [comment]
Ok, you have a grayscale base texture and an invisible overlay texture. But how do you get the colors on that texture? E.g where is defined that redstone is red and gold looks golden..

**Comment by TheLMiffy1111** [comment]
https://github.com/TheLMiffy1111/JAOPCA/blob/1.12/src/main/java/thelm/jaopca/proxy/ClientProxy.java#L33-L55

https://github.com/TheLMiffy1111/JAOPCA/blob/1.12/src/main/java/thelm/jaopca/ore/OreEntry.java#L104

https://github.com/TheLMiffy1111/JAOPCA/blob/1.12/src/main/java/thelm/jaopca/ore/OreColorer.java
