### ISSUE TITLE
[1.15.2] Question

### ISSUE THREAD

**Issue by TheUntamed** [TheLMiffy1111/JAOPCA#156]
A small programming question:
I'm trying to use the same method for block textures like you (one background image and one overlay) and for the item version of the block it just works fine, but not for the placed block:
![Screenshot_1](https://user-images.githubusercontent.com/48363903/80419120-d2d96f00-88d8-11ea-97d5-6b45e9cdc67e.jpg)
The background is simple vanilla stone the overlay the copper ore vein. Any idea what causes this problem?

**Comment by TheLMiffy1111** [comment]
You have to set the render layer of the block to cutout or translucent
https://github.com/TheLMiffy1111/JAOPCA/blob/1a2b867242cb0232599cc905f385b4f619180697/src/main/java/thelm/jaopca/client/events/ClientEventHandler.java#L61
