### ISSUE TITLE
[1.15.2] Flux recipes are incompatible... again

### ISSUE THREAD

**Issue by szeweq** [TheLMiffy1111/JAOPCA#158]
Loading Flux (version 4.16.0) with JAOPCA causes a crash while loading a world (see Szewek/Flux#28).

The `group` parameter was moved into a Builder class (see Szewek/Flux@1fad0ca) and this made recipe constructors incompatible. Later I added deprecated constructors so older JAOPCA versions can work properly without crashing (see Szewek/Flux@a77f250).

I suggest making changes in JAOPCA to fix this problem completely.

**Comment by TheLMiffy1111** [comment]
Fixed
