### ISSUE TITLE
[Suggestion] Configurable Ore Item Types

### ISSUE THREAD

**Issue by Bartz24** [TheLMiffy1111/JAOPCA#16]
Currently on 1.12, there are not any mods to add many variants of items, so I decided to add JAOPCA just to see if it would add anything to my pack with only thermal mods and actually additions.

The only thing added were molten fluids, which I'm going to use for recipes, but I was hoping I could add more.

I'm thinking that there could be config options to say, force mekanism clump items or ic2 purified ore items to be created even though those mods wouldn't be installed. This wouldn't add the recipes for them though

**Comment by TheLMiffy1111** [comment]
I'll put this in a json mod. Meanwhile I'll keep this open

**Comment by TheLMiffy1111** [comment]
Mod finished, closing
