### ISSUE TITLE
how to add

### ISSUE THREAD

**Issue by DabbingEevee** [TheLMiffy1111/JAOPCA#160]
just a question but how does jaopca detect materials?

what do i do to have it detect something

can i force a entry for this item?

**Comment by TheLMiffy1111** [comment]
Please specify version, as the 1.12 versions and the 1.14+ versions work slightly differently

**Comment by DabbingEevee** [comment]
i am currently using a 1.12.2 version, ive noticed that certain materials are not being recognized by the mod

since i also make mods, i would want my ingots to be recognized too

**Comment by TheLMiffy1111** [comment]
In 1.12.2, you need to register your ingots and ores into the ore dictionary right after you register them.
