### ISSUE TITLE
[1.15.2] Blocks added for empty tags

### ISSUE THREAD

**Issue by JaisDK** [TheLMiffy1111/JAOPCA#163]
Hi,

My mod adds a bunch of empty ingot tags so I can use them in recipes when they are populated from other mods. This however leads to JAOPCA creating block recipes for some of these ingots even when the tag is empty. I've tried running my mod without these empty tags, but unfortunately they have to exist for recipe validation.

![2020-07-21 00_00_55-Minecraft_ 1 15 2 - Singleplayer](https://user-images.githubusercontent.com/15868585/87986076-4d371b00-cae5-11ea-86c5-24730a594ee9.png)

**Comment by TheLMiffy1111** [comment]
You can add this to your recipe file to avoid adding empty tags:
```
"conditions": [
    {
        "type": "forge:not",
        "value": {
            "type": "forge:tag_empty",
            "tag": "forge:ingots/tungsten"
        }
    }
]

**Comment by JaisDK** [comment]
I indeed has errors in the conditions for some of the recipes. Thanks!
