### ISSUE TITLE
Adding Ex nihilo sequentia support

### ISSUE THREAD

**Issue by Irgendwer01** [TheLMiffy1111/JAOPCA#164]
Ex nihilo sequentia is a port  of Ex nihilo creatio to 1.15+, it would be nice if it would be possible adding support for it
link to it: https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia

**Comment by HydrogenC** [comment]
Plus one.

**Comment by TheLMiffy1111** [comment]
Added
