### ISSUE TITLE
[1.15.2] Thermal Mods Compatibility

### ISSUE THREAD

**Issue by NielsPilgaard** [TheLMiffy1111/JAOPCA#166]
Hey there!

CoFH mods are now on 1.15.2, and they could use some JAOPCA compat for their machines, namely Pulverizer, Induction Smelter, Multiservo Press & Centrifugal Seperator.

I hope you'll consider it despite being an older version.

**Comment by TheLMiffy1111** [comment]
Added in 3.2.0.15

**Comment by NielsPilgaard** [comment]
Awesome, thank you!
