### ISSUE TITLE
[1.15.2] Integrated Dynamics Compatibility 

### ISSUE THREAD

**Issue by NielsPilgaard** [TheLMiffy1111/JAOPCA#168]
Hi there!

Integrated Dynamics is available for 1.15.2, and it could use some JAOPCA compat for it's machines, namely the Squeezer and Mechanical Squeezer

I hope you'll (also) consider this request despite being an older MC version :)

**Comment by TheLMiffy1111** [comment]
Done

**Comment by NielsPilgaard** [comment]
Thank you!
