### ISSUE TITLE
[1.15.2] Immersive Engineering Compatibility

### ISSUE THREAD

**Issue by Unhook** [TheLMiffy1111/JAOPCA#169]
Hey there. JAOPCA used to have support for Immersive Engineering back in 1.12.2

Now that Immersive Engineering is available on 1.15 I was wondering if adding compat for their machines would be a possibility: specifically the alloy kiln, arc furnace, and blast furnace.

Even though this is an older version it'd be really appreciated.

**Comment by TheLMiffy1111** [comment]
I probably won’t do compatibility for Immersive Engineering on 1.14+ because it already handles ore processing pretty well
