### ISSUE TITLE
Crashed With TinkersC.

### ISSUE THREAD

**Issue by ghost** [TheLMiffy1111/JAOPCA#17]
[crash-2017-08-05_10.11.21-client.txt](https://github.com/TheLMiffy1111/JAOPCA/files/1202188/crash-2017-08-05_10.11.21-client.txt)
any idea?

**Comment by VladimirMangos** [comment]
I can confirm - same crash with TC

**Comment by Leo40Git** [comment]
Same crash here.

**Comment by TheLMiffy1111** [comment]
Will fix asap

**Comment by TheLMiffy1111** [comment]
k done

**Comment by ghost** [comment]
ok waiting for a release
