### ISSUE TITLE
[1.12.2] Please add TAIGA support

### ISSUE THREAD

**Issue by lazarusgreen** [TheLMiffy1111/JAOPCA#172]
I know that mod seems outdated, but despite its flaws it is an entertaining Tinkers Construct expansion and the new ores introduced by it would really benefit from being processing-compatible.

https://www.curseforge.com/minecraft/mc-mods/taiga-tinkers-alloying-addon

**Comment by AnjieMakesGames** [comment]
I second this.

**Comment by TheLMiffy1111** [comment]
Added in 2.3.0.0
