### ISSUE TITLE
[1.16.4] Certus quartz dust issue

### ISSUE THREAD

**Issue by frank89722** [TheLMiffy1111/JAOPCA#174]
Certus quartz dust from this mod can't use on other crafting and smelting recipes.

![image](https://user-images.githubusercontent.com/10683361/100377550-68460880-304c-11eb-817c-631ebd854c96.png)
![image](https://user-images.githubusercontent.com/10683361/100377829-00dc8880-304d-11eb-9736-d383cd484ca9.png)
![image](https://user-images.githubusercontent.com/10683361/100377841-08039680-304d-11eb-92dc-1b08ed15e157.png)
![image](https://user-images.githubusercontent.com/10683361/100378163-89f3bf80-304d-11eb-94de-a0c533a7c83a.png)

**Comment by TheLMiffy1111** [comment]
This is caused by AE2 tags not using the convention expected by JAOPCA, if it were the dust wouldn't be made.

**Comment by Letoric** [comment]
AE2 didn't change anything though, TheLMiffy1111. It's been that way for YEARS.
