### ISSUE TITLE
[1.15.2] Crash with the latest Create update (Create 0.3)

### ISSUE THREAD

**Issue by Vaelzan** [TheLMiffy1111/JAOPCA#179]
Due to a pretty major update on Create's end, JAOPCA's Create compat currently causes a crash when run alongside the newly released Create 0.3.

Specifically, the class `com.simibubi.create.content.contraptions.processing.ProcessingIngredient` no longer exists in the latest version.

Unfortunately I don't have a relevant crash report since Forge crashes later in the loading process, rather than exactly when this issue is first hit. Hopefully the above information should be enough to go off of though.

**Comment by TheLMiffy1111** [comment]
Fixed in new version
