### ISSUE TITLE
[1.10.2] Incompatibility with latest Mekanism release

### ISSUE THREAD

**Issue by heidrifx** [TheLMiffy1111/JAOPCA#18]
The latest version of JAOPCA (1.10.2-1.0.24) is incompatible with the latest release of Mekanism (9.2.3.97). While JAOPCA adds the various Crystals, Shards, Clumps and Dirty Dusts it doesn't add the required recipes to get them.

**Comment by TheLMiffy1111** [comment]
Should be a problem betweem Mekanism and JEI.

**Comment by heidrifx** [comment]
Alright, then I'm going to pass that on to the Mekanism issue tracker.
