### ISSUE TITLE
[1.16.4] Undergarden Compat

### ISSUE THREAD

**Issue by NielsPilgaard** [TheLMiffy1111/JAOPCA#183]
The mod Undergarden adds 4 new ores: 
- Utherium
- Regalium
- Cloggrum
- Froststeel

It'd be nice to be able to increase their output like so many other ores :)

**Comment by TheLMiffy1111** [comment]
Can you report this to Undergarden instead? JAOPCA expects individual tags for each ingot and ore. Undergarden currently only adds the items to the common tags, and didn’t add ores to item tags.

**Comment by NielsPilgaard** [comment]
Sure thing :)
