### ISSUE TITLE
Unusual crash on 1.12.2 related to Abyssalcraft

### ISSUE THREAD

**Issue by Sunconure11** [TheLMiffy1111/JAOPCA#185]
https://pastebin.com/C5CNs0wC

Tried to boot up a game and got... this.

Edit: Appears that something in Abyssalcraft got changed. I think this is fucking with this mod.

**Comment by gatoborrachon** [comment]
JAOPCA for 1.12 will never receive an update again?

**Comment by Biviho** [comment]
shouldn't it be possible to just at least disable the module if the new abyssalcraft is found, to avoid incompatibility?

edit: btw the crash happen with the alpha version of the 2.0 version of abyssalcraft, cause of the rewrite.

**Comment by TheLMiffy1111** [comment]
Should be fixed in 2.3.0.0 as it switched to the event based fuel handler
