### ISSUE TITLE
Dust from alltheores not smelting in 1.16 versions 

### ISSUE THREAD

**Issue by bruhmoment786** [TheLMiffy1111/JAOPCA#186]
Its very odd that JAOPCA works properly during ore processing functions such as enriching and crushing. However I am unable to smelt it and according to the mod menu there are no smelting functions associated with the dust. I tried zinc and nickel neither of them were smeltable. All other parts show up like clumps, just the dust isn't smeltable in a furnace nor a energized smelter.

**Comment by TheLMiffy1111** [comment]
AllTheOres adds dust smelting recipes to blasting instead. Please add your own recipes if you want them to be smeltable in a furnace.
