### ISSUE TITLE
[1.12.2]AdvancedRocketry crash issue.

### ISSUE THREAD

**Issue by inspiiree** [TheLMiffy1111/JAOPCA#193]
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-2.0.0-242-universal.jar
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.4.2-82-universal.jar  
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/tRsvNer8

## Description of the problem
Booting the game up.

Silfryi commented saying "This is JAOPCA's fault, not ours. Go tell them our plate press class name got updated if they want to continue adding support for it as they did before."

**Comment by voidsong-dragonfly** [comment]
Specifically, instead of being `zmaster587.advancedrocketry.blocks.BlockPress`, it's `zmaster587.advancedrocketry.blocks.BlockSmallPlatePress`

**Comment by inspiiree** [comment]
> Specifically, instead of being `zmaster587.advancedrocketry.blocks.BlockPress`, it's `zmaster587.advancedrocketry.blocks.BlockSmallPlatePress`

is this something that can be fixed by yourself?

**Comment by inspiiree** [comment]
I've fixed this incompatibility now @Silfryi it was much easier than I expected. :) thank you..

**Comment by TheLMiffy1111** [comment]
fixed
