### ISSUE TITLE
[1.12-Crash] Crash on startup with Advanced Rocketry

### ISSUE THREAD

**Issue by gatoborrachon** [TheLMiffy1111/JAOPCA#196]
When you try to load Advanced Rocketry and JAOPCA, you will get the following `NoClassDefFoundError` crash: https://pastebin.com/tE8Q0TQL

well, at least tell us how to disable this module, i don't even use the AR crusher.

**Comment by TheLMiffy1111** [comment]
Duplicate of #193 , update JAOPCA.

**Comment by gatoborrachon** [comment]
ok, many thanks
