### ISSUE TITLE
[Suggestion-1.12] Adding compat with the recently ported HBM's Nuclear Tech Mod 

### ISSUE THREAD

**Issue by gatoborrachon** [TheLMiffy1111/JAOPCA#198]
1.1.- [HBM's Nuclear Tech Mod](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/tree/1.12.2_test) is a mod focused on Bombs, Missiles, Guns, High Tech machines (like Centrifuges, Fission/Fusion/RBMK Reactors, Cyclotron, Particle Collider, etc) and one of these machines is called the [Ore Acidicer](https://ntm.fandom.com/wiki/Ore_Acidizer), which takes an Ore and converts it into a Crystal by using a Liquid (Hydrogen Peroxide) and Energy (similar process to what Mekanism does).

1.2.- Then each Cystals can:
1.2.1.- Be centrifuged in the [Centrifuge](https://nucleartech.fandom.com/wiki/Centrifuge) to get 4 dusts of the metal with 2 byproducts: 1 dust and 1 tiny dust.
1.2.2.- Be crushed in the [Shredder](https://ntm.fandom.com/wiki/Shredder) to get 3 dusts of the metal
1.2.3.- Be smelted in the Furnace to get 2 Ingots 

So my suggestion comes here: Why not add JAOPCA compat with the Ore Acidizer?

Also, to not open another issue, i had another suggestion:
2.- Why not make these Crystals (from my suggestion above) and the Purified Crushed Ores from IC2 be smeltable in the Tinkers' Construct Smeltery?

That's all, many thanks for reading.

**Comment by gatoborrachon** [comment]
mmm, well, i guess this will never be added? (just asking, no problem)

**Comment by TheLMiffy1111** [comment]
Added in 2.3.0.0

**Comment by gatoborrachon** [comment]
many thanks, let me test it as soon as i can, i hope many others find this as useful as i do
