### ISSUE TITLE
SAG mill second output

### ISSUE THREAD

**Issue by bortooo** [TheLMiffy1111/JAOPCA#2]
When you put an ore form extraplanets in the sag mill, the second output is cobblestone instead planet's stone.

![2017-05-07_10 36 46](https://cloud.githubusercontent.com/assets/28114042/25779179/97e68460-3312-11e7-8a09-870eea728d7a.png)

**Comment by TheLMiffy1111** [comment]
Ok, I'll work on a module config system on this

**Comment by bortooo** [comment]
Thanks!

**Comment by TheLMiffy1111** [comment]
Done, however the secondaries defaults to cobblestone, you will have to modify them manually

**Comment by bortooo** [comment]
Thanks again!
