### ISSUE TITLE
Pack Maker request: Common minecraft needs with no ore

### ISSUE THREAD

**Issue by wizard1399** [TheLMiffy1111/JAOPCA#20]
Hey,

I know your mod works by going through the forge ore dictionary and looking for ores missing certain items. Could you add a module that would do the same for some items from vanilla minecraft?

Molten glass?
Molten obsidian? Obsidian ingot/ nugget/ plate/ gear?
Molten emerald? ingot/nugget/ plate/ gear?
Molten diamond? ingot/ nugget/ plate/ gear?

I have noticed that many mods add some of this stuff for crafting, but usually forget about a liquid form.

**Comment by TheLMiffy1111** [comment]
nugget/plate/gear for gems are included as of now.
ingot/molten for gems don't make sense to me
won't do obsidian

**Comment by wizard1399** [comment]
Ingot/molten gems -> pour blocks of gems

**Comment by TheLimePixel** [comment]
Realistically Molten Gems are impossible.

**Comment by wizard1399** [comment]
You do realize you are coding a mod for minecraft right (sarcasm intended). In a world where you can punch trees with your bare fists, walking green dildos walk up and explode next to you, and water plus lava can make obsidian or cobblestone? The base game breaks the realm of realism when a block of diamond and emerald was added.to the game. I will defer to your choice, but, if your criteria is realism you may want to mod for a game where realism is a thing.

**Comment by TheLMiffy1111** [comment]
considering that tconstuct has molten emeralds, i might do molten gems.
wont do gem ingots though

**Comment by TheLMiffy1111** [comment]
try jaopcacustom
