### ISSUE TITLE
[1.12.2] Crash on start up - Incompatibility with Advanced Rocketry small plate press

### ISSUE THREAD

**Issue by Jlectric** [TheLMiffy1111/JAOPCA#200]
There seems to be incompatibility between the current version of JAOPCA (2.2.8.105) and the Advanced Rocketry small plate press. Using JAOPCA 2.2.8.103 seems to fix the issue. (I haven't tried 2.2.8.104)

Here's my crash report: https://paste.dimdev.org/najalaxovu.mccrash
JAOPCA 2.2.8.105
AdvancedRocketry 1.12.2-1.7.0-232
(JAOPCAAdditions 1.12.2-2.2.1.9)
(WrapUp-1.12-1.1.3)

I think this is a report of the same issue and an Advanced Rocketry dev seems to think the issue is to do with the plate press class name being updated: https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2032

Edit: I thought I should also add that Advanced Rocketry is currently still using XML as the recipe format for the plate press

**Comment by TheLMiffy1111** [comment]
JAOPCA 2.2.8.105 is built against Advanced Rocketry 2.0.0-242, so if you want to keep using Advanced Rocketry 1.7.0-232 you probably need to stay on JAOPCA 2.2.8.103

**Comment by Jlectric** [comment]
OK - Thanks

(Tested it and yes JAOPCA 2.2.8.105 launches just fine with Advanced Rocketry 2.0.0-242)
