### ISSUE TITLE
[1.12.2] Issue with GTCE integration

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [TheLMiffy1111/JAOPCA#201]
With JAOPCA 2.2.8.105 and GTCE 1.15.0.721, the following error was noticed in the log, [Error](https://pastebin.com/DJGNgU3V)

This was also with the addition of GTCE addon mod Gregicality.

**Comment by TheLMiffy1111** [comment]
Closing this for now as GTCE integration is removed for now in 2.3.0.0
