### ISSUE TITLE
Certain clean slurry to crystal recipes missing when Emendatus Enigmatica is installed

### ISSUE THREAD

**Issue by Mitchell-Swayn** [TheLMiffy1111/JAOPCA#203]
![image](https://user-images.githubusercontent.com/57333064/126524247-a4d531ea-2f79-499c-a795-28eaf7867b43.png)

Mekanism ore x5 recipes and items not generating. Only get dirty and clean slurry for the following materials: Cobalt, Nickel, Silver, Aluminum and Zinc

(Zinc is from Create)

Using version 3.4.0.9 for 1.16.5

**Comment by TheLMiffy1111** [comment]
Please check if this is fixed in 3.4.0.10
