### ISSUE TITLE
Datapack issue with Occultism

### ISSUE THREAD

**Issue by Irritated-Badger** [TheLMiffy1111/JAOPCA#204]
There is a datapack incompatibility between the latest version of Occultism and JAOPCA. I reported it both here and on the other mod's issue tracker. When creating or loading a world the "Datapack loading error"  screen appears. I've narrowed it down to these two mods. 

- Mincraft Version: 1.16.5
- Forge Version: 36.1.61
- Occultism Version: 1.7.0
- JOAPCA Version: 3.4.0.9

**Comment by klikli-dev** [comment]
A user posted a crashlog on the occultism GitHub repo: https://gist.github.com/Febilian/3d86f120b1935ebd1336f229b675343e  

See also https://github.com/klikli-dev/occultism/issues/306

**Comment by klikli-dev** [comment]
My best guess is that the recent change in Occultism 1.7.0 that added the property `ignore_crushing_multiplier` to crushing recipes causes this - based on the log my best guess is the compat layer needs to be updated. 

See also the related commit on occultism https://github.com/klikli-dev/occultism/commit/e41c086021dc6f6f3cf0305a5b9a9ac732c85704

**Comment by TheLMiffy1111** [comment]
Should be fixed in 3.4.0.10
