### ISSUE TITLE
JAOPCA causes datapack load error with the latest Thermal Foundation

### ISSUE THREAD

**Issue by Cynix32** [TheLMiffy1111/JAOPCA#205]
I recently updated my Thermal Foundation series mods to the latest build. Upon loading a world, a datapack loading error was thrown.

MC 1.16.5
Forge 36.2.2
JAOPCA-1.16.5-3.4.0.11.jar
thermal_foundation-1.16.5-1.3.0.jar

Console log:
https://pastebin.com/xtrs48pS

**Comment by digi-tal-it** [comment]
I can confirm this behaviour, same mod versions as mentioned above

https://pastebin.com/F64MVxTt

**Comment by KingLemming** [comment]
Yeah, basically you guys are directly accessing Thermal's recipe manager code, and the place where it exists has changed.

I don't foresee it changing again but in general if you have another way to do this, it might be preferable?

**Comment by DKLYNTLY** [comment]
how to isntall this

**Comment by CaptainBignose** [comment]
I can also confirm this behavior... I removed JAOPCA from my modpack and it loaded fine

**Comment by TheLMiffy1111** [comment]
Resolved in 3.4.0.12
