### ISSUE TITLE
Add support for RFTools Dimensions: Dimensional Shard Ore

### ISSUE THREAD

**Issue by RillingDev** [TheLMiffy1111/JAOPCA#21]
Mod: <https://minecraft.curseforge.com/projects/rftools-dimensions>
Ore Name: Dimensional Shard Ore (`rftools:dimensional_shard_ore`)
Item Name: Dimensional Shard (`rftools:dimensional_shard`)

**Comment by TheLMiffy1111** [comment]
Will add to OreDictInit.

**Comment by TheLMiffy1111** [comment]
Added
