### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by 1TruGod** [TheLMiffy1111/JAOPCA#210]
Installed the newly updated mod, and game crashes on startup/load.
Ive attached the crash report on pastebin.
https://pastebin.com/S9aAjJrn

**Comment by TheLMiffy1111** [comment]
This looks like a Oh The Biomes You'll Go problem, please check if it crashes without JAOPCA

**Comment by TheLMiffy1111** [comment]
This looks like a weird interaction with Oh The Biomes You'll Go and Sodium Reforged (Halogen) and have nothing to do with JAOPCA, please check if crash persists if JAOPCA is removed

**Comment by 1TruGod** [comment]
Crash does not persist if i remove latest version of jaopca. only occurs with latest version. crash goes away also if i downgrade jaopca to JAOPCA-1.16.5-3.4.0.12

**Comment by TheLMiffy1111** [comment]
Unable to recreate crash with JAOPCA, Tinkers' Construct, Oh The Biomes You'll Go, and Halogen.

**Comment by 1TruGod** [comment]
https://pastebin.com/iqgjhrrD

Another crash log from just now, did the same test, updated to new JAOPCA and then crashed. Reverted to old JAOPCA and no problems.
