### ISSUE TITLE
[1.12] Allow Magneticraft recipe registration to be completely disabled.

### ISSUE THREAD

**Issue by Ashen-sysadmin** [TheLMiffy1111/JAOPCA#211]
There is modified version of magneticraft that removes several classes: https://www.curseforge.com/minecraft/mc-mods/magnetic-engineering

It uses the same mod ID, and currently JAOPCA crashes when it is installed because JAOPCA looks for non-existent classes. If there was some way to completely disable certain mod support systems, then it would go a long way at improving compatibility with certain edge cases.

**Comment by Ashen-sysadmin** [comment]
Silfryi/Magneticraft/issues/2

**Comment by Ashen-sysadmin** [comment]
No it is not another mod's problem, The problem needs to be fixed on your side by allowing compat to be disabled in the config.

**Comment by RedRaspberry** [comment]
Hate to necro this issue, but is there any chance of this ever being fixed?

**Comment by TheLMiffy1111** [comment]
Closing this for now
