### ISSUE TITLE
Suggestion - Add Draconic Ore compatibility

### ISSUE THREAD

**Issue by ShiroETsuki** [TheLMiffy1111/JAOPCA#216]
As title states, it would be cool if you could add the draconic evolution ores as it is in beta and working now.

**Comment by TheLMiffy1111** [comment]
If Draconic Evolution adds tags in the format JAOPCA expects (and it seems like it does), it should be automatically supported. Have you actually tested it?

**Comment by TheLMiffy1111** [comment]
Closing for now
