### ISSUE TITLE
[1.18.1] [Suggestion] Add Create Crushing compatibility with Raw Ores and Raw Ore Blocks

### ISSUE THREAD

**Issue by ffuentesm** [TheLMiffy1111/JAOPCA#220]
For now, both Crushing and Milling recipes use the Ore black that can only be acquired via Silk Touch now in 1.18. 
So I suggest to add the Raw ore version of the recipes to gain access to the crushed ore variants.

**Comment by TheLMiffy1111** [comment]
Which crushing and which milling?

**Comment by ffuentesm** [comment]
Most are Crushing Wheel, only things that is millstone are bricks, clay, and non Ore/obsidian equivalent
![image](https://user-images.githubusercontent.com/44974827/151649933-d047733f-5e6c-42a2-8112-438b60d3cca4.png)

**Comment by TheLMiffy1111** [comment]
This is already a feature. JAOPCA assumes that raw material tags follow the new forge convention.

**Comment by ffuentesm** [comment]
Is not implemented, it only works with Ore blocks, not Raw ores
![image](https://user-images.githubusercontent.com/44974827/151669531-ebdb1782-9b39-406a-a663-5ade022aff2b.png)

Raw Ore and Raw Ore Blocks have different Forge Tags
![image](https://user-images.githubusercontent.com/44974827/151669555-0024976a-8768-415d-9306-910b4fa02f3e.png)
![image](https://user-images.githubusercontent.com/44974827/151669560-60acb7ec-ac98-4d80-bd8f-d325cb5abea1.png)

**Comment by TheLMiffy1111** [comment]
JAOPCA expects `forge:raw_materials/<material name>` which is the current forge convention and not `forge:raw_ores/<material name>` which AllTheOres uses, and assumes that the raw block does not exist if there is no tag with the former name. There will be no changes to this. You might want to report to AllTheOres instead.

![image](https://user-images.githubusercontent.com/6522061/151671284-1757425f-34f7-4277-bc9b-678506c5d892.png)
