### ISSUE TITLE
New update causes crash

### ISSUE THREAD

**Issue by NordicGamerFE** [TheLMiffy1111/JAOPCA#221]
# There is an issue where the newest update of the mod that crashes my modpack

**Forge - 36.2.23** 

| Crash | Version | 
| --- | :---: |
| Yes | 1.16.5.3.4.3.24 |
| Unknown | 1.16.5.3.4.3.23 |
| No | 1.16.5.3.4.2.22 |

## Links to logs
| Name | Link |
| --- | :---: |
| Crash Log | https://paste.gg/p/anonymous/92be292a0558473f948cb1c2891fab57 | 
| Latest Log | https://paste.gg/p/anonymous/29c26c4cb8ba4a0bbf08cf201301863a |

**Comment by TGurl** [comment]
I experienced the same issue, with the same MC version and the same crash logs.

MC: 1.16.5
OS: Linux
Launcher: GDLauncher

**Comment by TheLMiffy1111** [comment]
Fixed
