### ISSUE TITLE
[1.12.2] Better GalactiCraft and GalaxySpace support

### ISSUE THREAD

**Issue by v1993** [TheLMiffy1111/JAOPCA#223]
There are a few ways GalactiCraft and GalaxySpace support can be enchanted:

* Don't add blocks for GS's metals since they are already present (fixable in config for now)
* Detect titanium (with ilmenite ore) as material
* Detect lunar sapphires
* Detect silicon
* Recognize GS's Meteoritic Iron Ore as, well, ore of meteoritic iron

There might be more, but that's what I've found so far.

**Comment by TheLMiffy1111** [comment]
Added in 2.3.0.0
