### ISSUE TITLE
[1.18.1] Server crash: Tag forge:molten_brick used before it was bound

### ISSUE THREAD

**Issue by evhub** [TheLMiffy1111/JAOPCA#224]
Immediately after fully launching with JAOPCA included, the server crashes with
```
java.lang.IllegalStateException: Tag forge:molten_brick used before it was bound
```
and the crash is resolved when JAOPCA is removed.

See the full crash report here: https://gist.github.com/evhub/6204b42e3fb3665e42a7773a869289dc

I'm running Minecraft 1.18.1, Forge 39.0.75, and JAOPCA 4.0.1.1.

**Comment by TheLMiffy1111** [comment]
Can you try removing Crossroads to see if it still crashes?

**Comment by evhub** [comment]
@TheLMiffy1111 Just tested it—I can confirm that without crossroads it doesn't crash.

**Comment by TheLMiffy1111** [comment]
You might want to make an issue on Crossroads, the crash seems to be caused by the way Crossroads parses fluid ingredients.
