### ISSUE TITLE
[ModCompat] Blue Skies ore compat

### ISSUE THREAD

**Issue by Warhand** [TheLMiffy1111/JAOPCA#226]
It doesn't seem like blue skies ore processing compat has been added yet, so I wanted to suggest it for 1.18

**Comment by TheLMiffy1111** [comment]
This is intentional on Blue Skies' side. See https://gitlab.com/modding-legacy/blue-skies/-/issues/81
If you want Blue Skies compat, please manually create a data pack with KubeJS or Open Loader that adds Blue Skies tags to the Forge namespace.

**Comment by Warhand** [comment]
Ah, I see, unsurprising this would be a conscious decision on the part of the Blue skies devs, they make some odd decisions in general.

Anyway, thanks for the response!
