### ISSUE TITLE
[1.12.2] Crucible recipe is not present in thaumatorium

### ISSUE THREAD

**Issue by Vftdan** [TheLMiffy1111/JAOPCA#227]
According to JEI, I can craft osmium native ore cluster using thaumcraft crucible, however if I put osmium ore into thaumatorium, such option doesn't appear.

Mods:
 * JAOPCA-1.12.2-2.2.8.103
 * Mekanism 1.12.2-9.8.3.390
 * Thaumcraft 1.12.2-6.1.BETA26

Modpack: MC Eternal 1.3.7.1

**Comment by TheLMiffy1111** [comment]
Are you sure that you have the Metal Purification research

**Comment by Vftdan** [comment]
Ah, sorry, no, I apparently skipped it, because I had vanilla ingots in abundance & did not know about that other clusters was added by JAOPCA.

And Thaumic JEI notifies me when I miss a research for arcane workbench recipe, but does not for crucible, so this could be the problem of my confusion.
