### ISSUE TITLE
Adds recipes with empty outputs, causing crashes

### ISSUE THREAD

**Issue by malte0811** [TheLMiffy1111/JAOPCA#229]
Crash log: https://gist.github.com/malte0811/15c5661af46a148253aac74a686332e3

See RCXcrafter/Materialis#18 and BluSunrize/ImmersiveEngineering#5290.

This happens because you're adding a recipe without an output (or rather an empty output): `jaopca:immersiveengineering.dust_to_material.starmetal`. This is not supported by IE; and even vanilla warns about it (e.g. on `jaopca:storage_blocks.to_material.shadow_steel`). The mods directly involved in the crash are:

- JAOPCA
- Immersive Engineering
- Silent Gear: Adds starmetal dust, but no ingot
- CookingForBlockheads: Queries all recipe outputs; just makes it crash immediately rather than at some random point
- Materialis: Adds the starmetal ingot tag with only a *non-mandatory* entry (from astral sorcery) ([here](https://github.com/RCXcrafter/Materialis/blob/0ccac695d3a1cc5f2c39c93c283a5110c4876f7f/src/generated/resources/data/forge/tags/items/ingots/starmetal.json))

**Comment by TheLMiffy1111** [comment]
JAOPCA shouldn't register recipes with empty outputs anymore.
