### ISSUE TITLE
Rendering Crash

### ISSUE THREAD

**Issue by TheLimePixel** [TheLMiffy1111/JAOPCA#23]
I installed version 1.12-2.2.1.38 and then I wanted to see what's new. So I started writing @jaopca in JEI and then I crashed:
https://pastebin.com/2e6Y9MNT

 As it has extra utilities in the crash log, I'm guessing that it has to do with the fact that the Resonating Redstone Crystal, which has the ore dict entry gemRedstone, has JAOPCA materials.

**Comment by TheLMiffy1111** [comment]
ok seems like i still have to get item overrides on that one

**Comment by TheLimePixel** [comment]
Well everything seems to be fine now.
