### ISSUE TITLE
[1.18.2] Tinkers Construct alloying compat

### ISSUE THREAD

**Issue by ParasiticSquid** [TheLMiffy1111/JAOPCA#233]
Basically what it says on the tin. Tinkers construct doesn't have a steel alloying recipe and none of the addons except materialis is updated, but the developer refuses to add steel alloying for some reason which is.. a odd choice but to each their own. Figured ore processing compatibility is right up JAOPCA's ally so would mention it here. Not sure about other alloys since I haven't gotten there in my modded world yet but if they don't exist they would be nice too. Stuff like electrum, invar, constantan, ect.

**Comment by TheLMiffy1111** [comment]
I don't think alloying is in the scope of JAOPCA as it requires three or more materials in each recipe, and JAOPCA only adds single material recipes.
