### ISSUE TITLE
[1.18.2] Smelting recipes not working

### ISSUE THREAD

**Issue by Mig979** [TheLMiffy1111/JAOPCA#238]
I'm playing Direwolf20 1.18.2 and I installed JAOPCA as I wanted to use Mekanism to process all my ores. Everything seems to work perfectly fine apart from Zinc from Create I can turn it into dust however the dust doesn't have the recipe to be smelted into ingots on most furnaces, I'm guessing this is not intended.

Here is a screenshot: https://i.imgur.com/IuXx6QG.png (there's nothing else past the Induction Smelter)

**Comment by TheLMiffy1111** [comment]
Please send a debug.log, if the smelting recipes could not be added there should be info there

**Comment by Mig979** [comment]
Here is the log: [debug.log](https://github.com/TheLMiffy1111/JAOPCA/files/9174672/debug.log)

**Comment by TheLMiffy1111** [comment]
Do you have a debug.log where you load a world?

**Comment by Mig979** [comment]
Here is the new log: [debug.log](https://github.com/TheLMiffy1111/JAOPCA/files/9175256/debug.log)

**Comment by TheLMiffy1111** [comment]
Neither JAOPCA nor KubeJS complained about the recipe being invalid, can you check if you can actually smelt the zinc?

**Comment by Mig979** [comment]
Yea, I have tried to smelt it but nothing happens.

https://i.imgur.com/Ek0Ooyj.png

**Comment by Mig979** [comment]
Ok I have just found out the same happens with Cobalt Dust, nothing happens when I try to smelt it. These seem to be the only two dusts added by JAOPCA on the modpack and both are not smelting in regular furnaces.

https://i.imgur.com/PRykMT4.png

https://i.imgur.com/jbUVy3j.png

**Comment by Mig979** [comment]
I installed the mods that were affects on a fresh install and I can't replicate the issue, I'm assuming it's something with the modpack I'm playing. I have managed to add these missing recipes through KubeJS. I'm closing the issue as this doesn't seem to be an issue with your mod.
