### ISSUE TITLE
[1.16.5]  Valhelsia 3 Mod Loading Error 

### ISSUE THREAD

**Issue by AlphablueIV** [TheLMiffy1111/JAOPCA#239]
The game will startup with no issues, but once the mod scan is complete, it'll display the error screen stating: 
"JAOPCA (jaopca) has failed to load correctly
		com.electronwill.nightconfig.core.io.ParsingException: Not enough data available" 

I should mention this didn't happen until I upgraded my GPU and CPU. I'll attach the provided crash report.
[crash-2022-07-23_12.46.58-fml.txt](https://github.com/TheLMiffy1111/JAOPCA/files/9174573/crash-2022-07-23_12.46.58-fml.txt)

**Comment by TheLMiffy1111** [comment]
Can you try deleting JAOPCA material configs? It might be that some config files were not saved properly

**Comment by AlphablueIV** [comment]
I deleted the material configs for JOAPCA, but it still fails to load and Titanium decided to join the fray with the same error. What exactly is meant by "Not enough data available"? 



[crash-2022-07-30_16.34.18-fml.txt](https://github.com/TheLMiffy1111/JAOPCA/files/9227761/crash-2022-07-30_16.34.18-fml.txt)
![2022-07-30](https://user-images.githubusercontent.com/109875259/182003785-0cfc0138-1adc-433d-b445-32b82b4df3f9.png)

**Comment by TheLMiffy1111** [comment]
It most likely means that the config file being read ended unexpectedly in a place where it breaks the TOML format. It seems like you would need to re-generate JAOPCA and Titanium module configs as well.
