### ISSUE TITLE
Version 1.12-2.2.1.38 is giving me empty worlds

### ISSUE THREAD

**Issue by digi-tal-it** [TheLMiffy1111/JAOPCA#24]
Today I updated Jaopca from Version 1.12-2.2.0.35 to 1.12-2.2.0.38. After loading my singelplayer worlds, it was completely empty. Had to switch back to version 35 and world loads fine.

I am using a modded 1.12, Forge 14.21.1.2443

**Comment by TheLMiffy1111** [comment]
What do you mean by "empty"?
Also can I see the log

**Comment by digi-tal-it** [comment]
I have made a screenshot: http://imgur.com/a/j0W5s

You can finde the log here: https://paste.ee/p/DGsdY

**Comment by TheLMiffy1111** [comment]
According to the log this issue should be the same as #23, will check.

**Comment by digi-tal-it** [comment]
Thanks for checking and keep up the good work!

**Comment by TheLMiffy1111** [comment]
I've uploaded a new version that might solve the problem

**Comment by TheLMiffy1111** [comment]
seems to be fixed

**Comment by digi-tal-it** [comment]
I can confirm, that it works now. Thanks for the quick fix!
