### ISSUE TITLE
[1.12.2]Some of the problems occurred with the latest version

### ISSUE THREAD

**Issue by ghost** [TheLMiffy1111/JAOPCA#243]
1.plates,gears,rods are not generate properly(only generate dusts,blocks and mek process lines)
2.Incorrectly generated blocks that already exist.
mainly botania(other mods doesn't appear this problem)
![QQ截图20220811174141](https://user-images.githubusercontent.com/103164772/184106393-49373549-a5df-4f7d-9c37-9c6ea1e52712.png)
3.nuclearcraft(include overhauled) blocks and dusts should not be generated(or add an option) because they are too many and not useful at all 
4.doesn't compact the subsidiary(like JAOPCAAdditions)

At the end,the latest version of the features are very useful(generating all the things that have oredict),thank so much for your work.

**Comment by TheLMiffy1111** [comment]
1. Plates, gears, and rods are passive modules, meaning that you have to specify in the config that you want them to be generated.
2. Botania doesn't seem to add block oredict, causing this problem. Could add a oredict module for this
3. You can turn them off in the config by adding "*" to the module blacklist of the materials
4. There are no plans to update JAOPCAAdditions to the 2.3 specification.

Also you can use Chinese here

**Comment by ghost** [comment]
位置在config/jaopca/modules
然后把passiveMaterialWhitelist = []里填入希望生成的材料？

**Comment by ghost** [comment]
确实如此，感谢
