### ISSUE TITLE
[1.12.2]How can I translate the materials

### ISSUE THREAD

**Issue by ghost** [TheLMiffy1111/JAOPCA#244]
The original lang is not useful 
![QQ截图20220817103212](https://user-images.githubusercontent.com/103164772/185021657-83ed97c8-5dfb-4e79-8d18-37246adb6025.png)

By the way, can I add custom parts(like JAOPCACustom)

**Comment by TheLMiffy1111** [comment]
The translation key is `jaopca.material.AstralStarmetal`

Yes, you can make custom forms (although I never documented the format sorry)

**Comment by ghost** [comment]
So will you make a wiki for it?

**Comment by Hydrogen897** [comment]
> So will you make a wiki for it?

Why not use the ContentTweaker?

**Comment by ghost** [comment]
I’ve already known how to use it,thank you
