### ISSUE TITLE
Certus Quartz blocks can be duped through JAOPCA's smeltery recipes

### ISSUE THREAD

**Issue by NielsPilgaard** [TheLMiffy1111/JAOPCA#247]
Using `JAOPCA-1.18.2-4.1.9.15`

Certus Quartz blocks are made with 4 Certus Quartz, but they can be melted down into 900mb of Molten Certus Quartz through Tinkers' Construct melting, with recipes created by JAOPCA. 900mb is equivalent to 9 Certus Quartz.

4 Certus -> Melts into 900mb Molten Certus -> Cast into 9 Certus -> ...

![image](https://user-images.githubusercontent.com/21295394/193127459-76f34134-e13c-44ff-9093-c8472dcbb3d0.png)
![image](https://user-images.githubusercontent.com/21295394/193127442-7cc73251-d45c-4d9c-81ce-2cc93e8a22da.png)
![image](https://user-images.githubusercontent.com/21295394/193127523-250ff523-2929-4276-a4c8-2052aa66d168.png)

Reported to the Enigmatica 8 issue tracker here: https://github.com/EnigmaticaModpacks/Enigmatica8/issues/288

**Comment by TheLMiffy1111** [comment]
The config feature added in 4.1.10.16 should resolve this

**Comment by NielsPilgaard** [comment]
Thanks!
