### ISSUE TITLE
crash with JAOPCA series and Thermal series in 1.12.2

### ISSUE THREAD

**Issue by DAmanc123** [TheLMiffy1111/JAOPCA#248]
mod loaded:Thermal series and JAOPCA,Wrapup,JAOPCAs singularities
and it just ceashed
details will shown as follow

do you know why and how to fix this problem plzzz

[crash-2022-10-19_08.31.15-server.txt](https://github.com/TheLMiffy1111/JAOPCA/files/9816741/crash-2022-10-19_08.31.15-server.txt)

**Comment by DAmanc123** [comment]
how i can solve the problem

**Comment by TheLMiffy1111** [comment]
You submitted the wrong crash report i think

**Comment by DAmanc123** [comment]
but its the exactly the report and im sure about that

**Comment by TheLMiffy1111** [comment]
There is no JAOPCA in the report

**Comment by DAmanc123** [comment]
ohh

**Comment by DAmanc123** [comment]
sorry

**Comment by DAmanc123** [comment]
[crash-2022-10-18_17.00.00-server.txt](https://github.com/TheLMiffy1111/JAOPCA/files/9819282/crash-2022-10-18_17.00.00-server.txt)
this is the true crash report

**Comment by DAmanc123** [comment]
sorry again for what i just said

**Comment by TheLMiffy1111** [comment]
Duplicate of #63 

You have a really outdated version, update JAOPCA to at least 2.2.6.83

**Comment by DAmanc123** [comment]
but the newest JAOPCAs singularities suggested me this version

**Comment by DAmanc123** [comment]
but i will try it now

**Comment by TheLMiffy1111** [comment]
That is the minimum required version, not the recommended

**Comment by DAmanc123** [comment]
oh~ i see

**Comment by TheLMiffy1111** [comment]
You should update to 2.2.8.106 which is the newest version that should work with JAOPCASingularities

**Comment by DAmanc123** [comment]
wait a while please,im trying now~

**Comment by DAmanc123** [comment]
well it crashed
[crash-2022-10-19_18.15.44-server.txt](https://github.com/TheLMiffy1111/JAOPCA/files/9819491/crash-2022-10-19_18.15.44-server.txt)

**Comment by TheLMiffy1111** [comment]
Duplicate of #128

Use [Embers Rekindled](https://www.curseforge.com/minecraft/mc-mods/embers-rekindled) instead of Embers

**Comment by DAmanc123** [comment]
YES!It really worked!THANK YOU VERY MUCH!You really helped me a lot!THANK YOU!
