### ISSUE TITLE
1.12.1 JAOPCA Causing texture Errors

### ISSUE THREAD

**Issue by mcfilmmakers** [TheLMiffy1111/JAOPCA#25]
Latest version of JAOPCA running on Forge 2463 is causing texture errors in vanilla:

[https://pastebin.com/Vg69KF7R](https://pastebin.com/Vg69KF7R)

Removing JAOPCA stops the error.

**Comment by TheLMiffy1111** [comment]
it was a thing in my fluid model, ignore it
