### ISSUE TITLE
Can't launch a singleplayer world with Futurepack and JAOPCA [1.16.5]

### ISSUE THREAD

**Issue by craftish37** [TheLMiffy1111/JAOPCA#250]
JAOPCA v: 3.4.3.26
Futurepack v: 31.3.7008

Got this error before the crash report :
![image](https://user-images.githubusercontent.com/63811617/198844275-a1c5687d-7547-4af1-a0fe-0eeda5a9f4f8.png)

For any other infos, don't hesitate to ask, I'll do my best 👌

**Comment by TheLMiffy1111** [comment]
Downgrade to Futurepack 31.3.7005 for now

**Comment by TheLMiffy1111** [comment]
Should be fixed in 3.4.4.29
