### ISSUE TITLE
Extra Fluorite combiner recipe

### ISSUE THREAD

**Issue by pupnewfster** [TheLMiffy1111/JAOPCA#251]
JAOPCA seems to add extra recipes for combining fluorite dust with cobble/cobbled deepslate that takes 5 fluorite dust + the secondary input. This seems like an oversight given the fact that:
1. Mekanism already provides a combiner recipe to create fluorite ore out of fluorite dust
2. It drastically changes the balancing depending on the order the recipes are loaded/chosen as the built in Mekanism recipes require 14 fluorite dust not 5.

To fix this in the pack I am working on I had to in `config/jaopca/modules/mekanism_compat.toml` blacklist fluorite in the `toOreMaterialBlacklist`

JAOPCA: 4.2.1.2
Forge: 43.1.47
Mekanism: 10.3.5

**Comment by TheLMiffy1111** [comment]
Should be fixed in 4.1.11.17 and 4.2.2.3
