### ISSUE TITLE
Missing Mekanism compat recipes for when there is no raw ore

### ISSUE THREAD

**Issue by pupnewfster** [TheLMiffy1111/JAOPCA#252]
I am not sure if this is due to defining these materials by adding existing types to blockTags and itemTags in the main config for JAOPCA, but it seems some ores (namely ones that are ore smelted to ingot rather than having raw ore) do not have all of the expected recipes created even with `ingotLegacy` set to `true`.

For example in the pack I am working on that has divine rpg, I added `"forge:ores/torridite", "forge:storage_blocks/torridite"` to the `blockTags.customDefined` and added `"forge:ingots/torridite", "forge:nuggets/torridite", "forge:ores/torridite", "forge:storage_blocks/torridite"` to the `itemTags.customDefined`. (I also had to add the divine rpg items and blocks to those corresponding tags via datapack). For this material `torridite`, JAOPCA only seems to create a dust variant and adds an enrichment chamber recipe for creating two dust from one ore, and adds a recipe to smelt the dust into ingots. I was also expecting items, slurries, and recipes for the rest of Mekanism's 5x ore processing chain to be created as while there is no raw ore and I don't think any should be created by JAOPCA, Mekanism's 5x ore processing chain still works the same as it always has when provided with the actual ore blocks.

In contrast ores I do a similar thing for from divine rpg that do have raw ores (and that I define the tags for) do have the entire set of items and recipes properly created by JAOPCA.

JAOPCA: 4.2.1.2
Forge: 43.1.47
Mekanism: 10.3.5

**Comment by TheLMiffy1111** [comment]
Should be fixed in 4.1.11.17 and 4.2.2.3
