### ISSUE TITLE
arc furnace producing incorrect ammount of ingots

### ISSUE THREAD

**Issue by DelviousCrafts** [TheLMiffy1111/JAOPCA#253]
Standard JAOPCA recipes in the immersive engineering arc furnace are giving one ingot for blocks of raw ore with a 50% chance for another and one ingot for ore blocks. Standard recipes provided by immersive engineering provide 13 ingots with a 50% chance for another for raw ore blocks, and 2 ingots for ore blocks. 

Versions:
Minecraft: 1.18.2
Forge: 40.1.84
JAOPCA: 4.1.11.17

**Comment by TheLMiffy1111** [comment]
Should be fixed in 4.1.11.19 and 4.2.3.4
