### ISSUE TITLE
[1.12.2]Translations are always reset automatically.

### ISSUE THREAD

**Issue by Ironnoob73** [TheLMiffy1111/JAOPCA#257]
The lang file is provided in Jaopca's config, but the lang file has many mistakes, and although it can be modified, the game will always inadvertently reset the file to the previous wrong version.

**Comment by TheLMiffy1111** [comment]
You should be able to set the update interval in the config to a very high value to avoid the mod automatically replacing the language files.
If you think there are mistakes or inconsistencies you can fix please submit a pull request to the material localization repo.
