### ISSUE TITLE
[1.12.2]How can I add custom parts

### ISSUE THREAD

**Issue by ghost** [TheLMiffy1111/JAOPCA#259]
I guess we can generate custum material parts just like ContentTweaker.
I tried to add an .toml file in config/jaopca/modules like this![image](https://user-images.githubusercontent.com/103164772/209306962-002f84cd-f65c-4113-8e08-aa77a438a2f9.png)but it was useless.
Can you tell me how to or it's not possible.

**Comment by TheLMiffy1111** [comment]
There should be a custom.json in the jaopca folder
I haven't documented the format yet, but try putting this into the json file
```
[
    {
        "name": "singularity",
        "type": "item",
        "materialTypes": [],
        "defaultMaterialBlacklist: []
    }
]
```

**Comment by ghost** [comment]
I found custom_form.json and put 
![image](https://user-images.githubusercontent.com/103164772/209455513-a14dcda2-452f-4be8-b081-700b3b2b5a04.png)
But it doesn't seem to create any items

**Comment by TheLMiffy1111** [comment]
Sorry, forgot to specify the values in materialTypes
Try replacing the materialTypes line with
```
"materialTypes": ["ingot", "gem", "crystal", "dust", "ingot_plain", "gem_plain"]
```
You can remove the material types you don't want

**Comment by ghost** [comment]
Thank you,I also want to know if I can add custom materialTypes?

**Comment by TheLMiffy1111** [comment]
There is no way to add custom material types and materials, and these are all the material types.
If you want custom materials you should probably use ContentTweaker because what JAOPCA does is generate items based on existing items.

**Comment by ghost** [comment]
OK
