### ISSUE TITLE
[1.19] Recipes do not get added when FastSuite is added

### ISSUE THREAD

**Issue by sciguyryan** [TheLMiffy1111/JAOPCA#260]
Hi!

I've run into a weird issue and I'm not sure if it's configuration issue or an actual bug.

I'm running a custom mod pack that have several ores that can be processed with Mekanism using JAOPCA, but the fluids and items don't appear to have any associated recipes. One of them is Nickel, the clean and dirty slurry fluids are present, but there are no recipes associated with them. The slurry would usually first be cleaned, then crystallized into crystals. The crystal items are present but also don't have any recipes associated with them either.

I wanted to get some feedback here before I attempt to add some KubeJS scripts to try and fix things.

**Comment by TheLMiffy1111** [comment]
Can you submit your debug.log?

**Comment by sciguyryan** [comment]
Yeah, sure. I should probably have included this with the original report in any event.

[debug.log](https://github.com/TheLMiffy1111/JAOPCA/files/10400024/debug.log)

**Comment by TheLMiffy1111** [comment]
It seems that in your modpack JAOPCA's mixin to add recipes was successfully added but isn't actually ran for some reason. However, I could not replicate the issue here with mods that add recipe manager mixins. Could you do a binary search (removing roughly half of the mods each time to see if the problem persists) to see if any other mods could be interfering?

**Comment by sciguyryan** [comment]
> It seems that in your modpack JAOPCA's mixin to add recipes was successfully added but isn't actually ran for some reason. However, I could not replicate the issue here with mods that add recipe manager mixins. Could you do a binary search (removing roughly half of the mods each time to see if the problem persists) to see if any other mods could be interfering?

The pack currently contains around 320 mods, I can certainly try but it might take me a while.

**Comment by sciguyryan** [comment]
It took me a while, but it appears to be as a result of the FastSuite mod, which can be found here:

https://www.curseforge.com/minecraft/mc-mods/fastsuite

**Comment by TheLMiffy1111** [comment]
Should be fixed in 4.2.4.7
