### ISSUE TITLE
Crash ( MC 1.12.2 )

### ISSUE THREAD

**Issue by Kasia1403** [TheLMiffy1111/JAOPCA#261]
[crash-2023-01-28_08.13.28-client.txt](https://github.com/TheLMiffy1111/JAOPCA/files/10526179/crash-2023-01-28_08.13.28-client.txt)
[debug.log](https://github.com/TheLMiffy1111/JAOPCA/files/10526180/debug.log)
[latest.log](https://github.com/TheLMiffy1111/JAOPCA/files/10526181/latest.log)

**Comment by TheLMiffy1111** [comment]
Remove JAOPCACustom

**Comment by Kasia1403** [comment]
So JAOPCA Custom does not work with JAOPCA Singularities addon ?

**Comment by TheLMiffy1111** [comment]
JAOPCACustom does not and will not support JAOPCA 2.3+, as its functionality has been integrated into JAOPCA 2.3+

**Comment by Kasia1403** [comment]
Removed JAOPCA Custom and still crashing.

[debug.log](https://github.com/TheLMiffy1111/JAOPCA/files/10527060/debug.log)
[latest.log](https://github.com/TheLMiffy1111/JAOPCA/files/10527061/latest.log)
[crash-2023-01-28_12.03.18-client.txt](https://github.com/TheLMiffy1111/JAOPCA/files/10527064/crash-2023-01-28_12.03.18-client.txt)

**Comment by TheLMiffy1111** [comment]
Remove JAOPCAAdditions, it's unlikely that I will update that mod to JAOPCA 2.3+.
Also remove JAOPCA Ore Chunks as that mod also hasn't updated to JAOPCA 2.3+. If you still need it, consider reporting to them.
