### ISSUE TITLE
[1.19.2] Crash With IndustrialCraft 2 Experimental 

### ISSUE THREAD

**Issue by Uptobillion** [TheLMiffy1111/JAOPCA#262]
![image](https://user-images.githubusercontent.com/28522459/215321772-9ad542c3-0ab3-4a73-889d-825a3102b8a0.png)
[crash-2023-01-29_19.00.37-fml.txt](https://github.com/TheLMiffy1111/JAOPCA/files/10529602/crash-2023-01-29_19.00.37-fml.txt)
IC2: https://jenkins.ic2.player.to/job/IC2/job/1.19/

**Comment by TheLMiffy1111** [comment]
Game should no longer crash in 4.2.5.8.
