### ISSUE TITLE
[1.12.2]2.3+ not support GTCE

### ISSUE THREAD

**Issue by SYFH** [TheLMiffy1111/JAOPCA#263]
2.2+ is support
![2 2+](https://user-images.githubusercontent.com/12558049/216027342-9536a1ff-ab2b-446b-b24c-89c533ba2e30.png)
but something is missing in 2.3+
![2 3+](https://user-images.githubusercontent.com/12558049/216027649-71e2095d-e7df-458e-85dc-7e6dee17c5cc.png)
config file without any changes

**Comment by TheLMiffy1111** [comment]
2.3+ changed some modules to passive modules that don't add anything unless configured to do so.
