### ISSUE TITLE
Missing mekanism ore processing items in Direwolf20 1.19

### ISSUE THREAD

**Issue by xBoBx78** [TheLMiffy1111/JAOPCA#264]
Missing all shards, dirty dusts, clumps, and crystals from mekanism when running on direwolf20 1.19 modpack.  The clean/dirty slurries still exist with the recipes.  Sounded similar to issue #260 but I was already running 4.2.4.7.

Updating to 4.2.5.8 and removing FastSuite did not resolve the issue.

Attaching debug.log:
[debug.log](https://github.com/TheLMiffy1111/JAOPCA/files/10593595/debug.log)

**Comment by TheLMiffy1111** [comment]
Can you try reporting this issue to FTB? I tried running Direwolf20 with only the mods and the recipes loaded normally, so it might be the configs or the scripts.

**Comment by TheLMiffy1111** [comment]
Found the problem, Direwolf20 removed most of the JAOPCA items for unification, causing many of JAOPCA's recipes to not be added. Report to FTB.

Temporary fix would be to go to `<KubeJS Folder>/startup_scripts/global.js` and remove all JAOPCA items from the `global['unUnified']` list.

**Comment by xBoBx78** [comment]
Thanks @TheLMiffy1111 I'll reach out to FTB.
