### ISSUE TITLE
[1.19.2] Can't process any raw aluminum and uranium in the pulverizer

### ISSUE THREAD

**Issue by Peca21** [TheLMiffy1111/JAOPCA#265]
There is no recipe raw ore -> dust in a pulverizer for aluminium and uranium
Not sure if thermal or JAOPCA bug
[Zip of a debug log because its too big](https://github.com/TheLMiffy1111/JAOPCA/files/10608478/debug.zip)
[Mod List](https://paste.ee/p/Iaz7n)
Forge 43.2.4
![image](https://user-images.githubusercontent.com/13818400/216764246-3a2b68e7-b9ac-4275-b97e-b07ce2480eb2.png)
Items in the chest can't go into a pulverizer

**Comment by TheLMiffy1111** [comment]
JAOPCA doesn't add Thermal recipes for aluminium and uranium if Immersive Engineering and Thermal Integration is loaded to prevent JAOPCA from potentially overriding the recipes Thermal Integration adds. It seems that Thermal Integration doesn't have pulverizer recipes for Immersive Engineering raw aluminium and raw uranium right now.
