### ISSUE TITLE
Add Raw Ores (Suggestion)(1.18/1.19)

### ISSUE THREAD

**Issue by Gitcrafter** [TheLMiffy1111/JAOPCA#268]
Hello, can you make JAOPCA generate Raw Ores and Raw Ore Blocks for Metal-based Materials, that have an Ore and Ingot, but no Raw Ore and Raw Ore Block (like Draconic Evolutions Draconium), preferably also for Ingots from Metals, that don´t have an Ore (like Bigger Reactors Cyanite)

**Comment by TheLMiffy1111** [comment]
JAOPCA will not add raw materials and raw storage blocks for materials without raw materials as I consider that if a material does not have raw materials, it is intended to be that way.
