### ISSUE TITLE
Uranium Chunk not being able to be macerated under IC2 for IC2 Crushed Uranium.

### ISSUE THREAD

**Issue by Lion4K** [TheLMiffy1111/JAOPCA#27]
I don't know if I should report the error here or at IC2's so i'm doing both sides. I'd figured it was here mostly because IE's Uranium still working on IC2 macerator, but JAOPCA Uranium is not.

**Comment by TheLMiffy1111** [comment]
um what chunk

**Comment by Lion4K** [comment]
It's called uranium chunk, like all other ores, like iron chunk, etc

**Comment by TheLMiffy1111** [comment]
The only chunk in JAOPCA is for Ex Nihilo

**Comment by Lion4K** [comment]
Yes, for ExNihilo, the uranium you get on that you cannot use to make IC2 uranium, only IE uranium.

**Comment by TheLMiffy1111** [comment]
nope

**Comment by Lion4K** [comment]
Ok, thanks for support.

PS: You might as well remove the IndustrialCraft name from the list of Supported mods, since you don't really support it, right? Unless half mod support counts.

**Comment by TheLMiffy1111** [comment]
Make sure you know how the mod works before submitting an issue.
