### ISSUE TITLE
[1.7.10] Endium from Hardcore Ender Expansion mislabeled 

### ISSUE THREAD

**Issue by CJCWIS** [TheLMiffy1111/JAOPCA#271]
Endium from Hardcore Ender Expansion (HEE) is mislabeled as "Hee Endium" Instead of just "Endium".

![image](https://user-images.githubusercontent.com/23131218/224763930-f6e92906-1518-4867-a7cf-5f11358d2cbe.png)

**Comment by TheLMiffy1111** [comment]
Added HeeEndium to material localization
