### ISSUE TITLE
[1.7.10] Crash when start a server

### ISSUE THREAD

**Issue by quentin452** [TheLMiffy1111/JAOPCA#272]
[crash-2023-03-16_08.13.45-server.txt](https://github.com/TheLMiffy1111/JAOPCA/files/10987736/crash-2023-03-16_08.13.45-server.txt)

**Comment by TheLMiffy1111** [comment]
Can you check if W.0.3.6 fixes the issue

**Comment by quentin452** [comment]
i will try

**Comment by quentin452** [comment]
seem to be not fixed in w0.3.6

**Comment by TheLMiffy1111** [comment]
Can you check if W.0.3.7 fixes the issue

**Comment by quentin452** [comment]
it seem to be working
