### ISSUE TITLE
Disable Silent's Gems compat

### ISSUE THREAD

**Issue by Mat1212fr** [TheLMiffy1111/JAOPCA#273]
Hello my problem is simple: after installing JAOPCA, when I restarted my game I sifted some gravel thanks to Ex Nihilo and I got large quantities of gems from Silent's Gems. So I ask if it is possible to disable the compatibility between JAOPCA and Silent's Gems and how to do it.
Thanks in advance

![image](https://user-images.githubusercontent.com/99351856/226162840-dbcf61da-5004-4d8a-bad0-8fd648ebadea.png)
_(too many gems in one sifting)_

**Comment by TheLMiffy1111** [comment]
Which version of JAOPCA are you using

Assuming 1.16 you might want to just disable the `exnihilosequentia_non_ingot` module by putting `"*"` in its material blacklist

**Comment by Mat1212fr** [comment]
You guessed right, the exact version is "JAOPCA-1.16.5-3.4.3.26.jar". Should I restart the game?

**Comment by TheLMiffy1111** [comment]
Yes

**Comment by Mat1212fr** [comment]
Thank you very much, and thank you for your speed ♥

**Before**
![Capture d'écran 2023-03-19 110726](https://user-images.githubusercontent.com/99351856/226169113-a2154f02-d9a1-4afc-849c-62b7830cdaa1.png)

**After**
![Capture d'écran 2023-03-19 112437](https://user-images.githubusercontent.com/99351856/226169134-79cb1143-dde4-41cd-a270-50c970ef1cdb.png)
