### ISSUE TITLE
Support Moar TCon

### ISSUE THREAD

**Issue by ghost** [TheLMiffy1111/JAOPCA#274]
I've found that the materials in Moar TCon are not identified by JAOPCA,it'll be great if all the materials can have mekanism ore process support.
mod link:https://www.curseforge.com/minecraft/mc-mods/more-tcon

**Comment by DabbingEevee** [comment]
yeah im not sure why my materials are not identified lol. ill look into it once I have a chance.

**Comment by TheLMiffy1111** [comment]
Moar TCon registers oredict at recipe registration, while JAOPCA requires oredict to be registered at item registration.

**Comment by DabbingEevee** [comment]
as of the latest beta, this as since been resolved.
