### ISSUE TITLE
[1.19.2] Intermittent crash durring server load

### ISSUE THREAD

**Issue by DelviousCrafts** [TheLMiffy1111/JAOPCA#275]
JAOPCA causes a crash intermittently while loading on a server. Does not happen every time the server loads, but enough to be a nuisance. Created during construct event phase.

Versions:
- Minecraft: 1.19.2
- Forge: 43.2.8
- JAOPCA: 4.2.7.13

Crash Report: 
[crash-2023-04-06_12.49.19-fml.txt](https://github.com/TheLMiffy1111/JAOPCA/files/11174046/crash-2023-04-06_12.49.19-fml.txt)

**Comment by TheLMiffy1111** [comment]
Can you try reporting this to Moonlight Lib?

**Comment by TheLMiffy1111** [comment]
Can you try reporting this to Moonlight?
MehVahdJukaar/Moonlight#54 seems to be related

**Comment by aaronhowser1** [comment]
I am also having this: https://gist.github.com/aaronhowser1/57e2ca1e580c588bf1c1cddb88dad918

**Comment by DelviousCrafts** [comment]
Closing this issue as it seems to have been resolved through moonlight updates
