### ISSUE TITLE
1.18.2 Index 2 out of Bounds for length 2 (crash on startup)

### ISSUE THREAD

**Issue by border999** [TheLMiffy1111/JAOPCA#276]
https://gist.github.com/border999/f5f9554c452294a533915780aa8fbfad
If you have any questions feel free to ask.

**Comment by TheLMiffy1111** [comment]
This probably is caused by an interaction between JAOPCA, JSON Things, and ModernFix, you might want to report to ModernFix

**Comment by border999** [comment]
issue resolved on Modernfixs side
