### ISSUE TITLE
[1.16.5] JAOPCA, Futurepack and Applied Energistics 2 world creation crash

### ISSUE THREAD

**Issue by sirben99** [TheLMiffy1111/JAOPCA#277]
Hey!

I have a crash when creating a world, with only JAOPCA, Applied Energistics 2 and Futurepack mod installed.

Im not sure whos to blame here, so i made an issue about this to here and Futurepack mods issue tracker (Applied automaticly closed the issue, since its unsupported version). You can find Futurepacks crash report [here
](https://github.com/mcenderdragon/Futurepack-API/issues/967)
1. Install Futurepack, Applied Energistics 2 and JAOPCA mods
2. Create a world
3. Crash

Minecraft Version: 1.16.5
Forge Version: 36.2.39
Futurepack Version: Futurepack-1.16.5-31.3.7008
Applied Energistics 2 Version: appliedenergistics2-8.4.7
JAOPCA Version: JAOPCA-1.16.5-3.4.3.26

Latest.log: https://pastebin.com/PHzJTfHp
Crash report: https://pastebin.com/R1eRwPh6
Debug.log: https://pastebin.com/2QcGBgbm

**Comment by TheLMiffy1111** [comment]
Duplcate of #250
