### ISSUE TITLE
Electrodynamics 1.19.2 JSON format change

### ISSUE THREAD

**Issue by skiprocks999** [TheLMiffy1111/JAOPCA#278]
Hello,

I am one of the devs for electrodynamics, and I tweaked the recipe JSON syntax for machines to now include processing time and usage per tick fields for one of the 1.19.2 updates we did. I didn't realize electro was popular enough to be noticed by a mod like this, or I would have said something. This necessitates every electrodynamics recipe JAOPCA has to have these fields added in order to fix the issue. Let me know what the easiest way to fix this will be.

Thanks in advance

**Comment by TheLMiffy1111** [comment]
Updated JAOPCA's recipe JSON generation to include the processing time and usage per tick fields, so this should be fixed in JAOPCA 4.2.7.14
