### ISSUE TITLE
Can you please add Iridium?

### ISSUE THREAD

**Issue by Lion4K** [TheLMiffy1111/JAOPCA#28]
For IC2 most advanced stuff.

**Comment by TheLMiffy1111** [comment]
This is a mod that adds stuff based on the ore-based materials other mods add, so probably not.

**Comment by Lion4K** [comment]
Well, it's, iridium ORE so.

**Comment by TheLMiffy1111** [comment]
JAOPCA needs a ingot, gem, or dust form in order for a material to be supported

**Comment by Lion4K** [comment]
Iridium comes in Ore and Shard.
You can maybe make so the chunk contains 1 shard that can be compressed into the ore. or something like that.

**Comment by Lion4K** [comment]
or maybe the same way diamonds and emeralds spawn.
A very, tiny, small, % of dropping an iridium shard.

**Comment by TheLMiffy1111** [comment]
nope

**Comment by Lion4K** [comment]
Ok, thanks for support.

PS: You might as well remove the IndustrialCraft name from the list of Supported mods, since you don't really support it, right? Unless half mod support counts.

**Comment by TheLMiffy1111** [comment]
Make sure you know how the mod works before submitting an issue.
