### ISSUE TITLE
1.20.1 crash on launch

### ISSUE THREAD

**Issue by Flame1211** [TheLMiffy1111/JAOPCA#283]
crashing when trying to launch the game, disabling the mod fixes it. 
forge 47.1.3
mod 4.4.0.0

[modlist.txt](https://github.com/TheLMiffy1111/JAOPCA/files/12138033/modlist.txt)
[latest.log](https://github.com/TheLMiffy1111/JAOPCA/files/12138038/latest.log)
[crash-2023-07-23_00.57.39-client.txt](https://github.com/TheLMiffy1111/JAOPCA/files/12138039/crash-2023-07-23_00.57.39-client.txt)

**Comment by Flame1211** [comment]
ive included my modlist so you can import it into curseforge if needed, the latest log and the latest crashlog

**Comment by TheLMiffy1111** [comment]
Should be fixed in 4.4.0.1
