### ISSUE TITLE
[1.12.2] Coins Question

### ISSUE THREAD

**Issue by Kasia1403** [TheLMiffy1111/JAOPCA#284]
What are coins for ? I can't find recipes in JEI/HEI.

**Comment by TheLMiffy1111** [comment]
The older 1.12.2 version's coins was made to be used with Thermal Expansion, you'd maky them wiss a coin compressor, and you could generate power with them.
The new 1.12.2 version removed recipes associated with them, you'd need to manally add them back.

**Comment by Kasia1403** [comment]
What if I don't use Thermal Expansion ?
