### ISSUE TITLE
Crash updating from 4.2.7.14 to 4.2.7.15

### ISSUE THREAD

**Issue by kurtramone** [TheLMiffy1111/JAOPCA#285]
Hello, I have a custom modpack and when I just updated your mod got a crash. Can you help? Using previous version I have no issues.

Versions
MC 1.19.2
Forge: 43.2.21
JAOPCA: 4.2.7.15 updated from 4.2.7.14
[crash-2023-09-07_14.54.26-client.txt](https://github.com/TheLMiffy1111/JAOPCA/files/12552204/crash-2023-09-07_14.54.26-client.txt)

**Comment by TheLMiffy1111** [comment]
This feels similar to #283
In these updates I switched to FG6 so probably related to that

**Comment by kurtramone** [comment]
Using previous version is normal, so, when/if you update/fix I'll test and let you know

**Comment by TheLMiffy1111** [comment]
Should be fixed in 4.2.8.16

**Comment by kurtramone** [comment]
New version looks solid, no crashes so far. Thanks.
