### ISSUE TITLE
[1.10.2] Crash on startup

### ISSUE THREAD

**Issue by heidrifx** [TheLMiffy1111/JAOPCA#29]
Game crashes on startup. I'm using JAOPCA Singularities which shouldn't interfere and blacklisted some modules (some item specific, some global).

Link to crash log: https://pastebin.com/FVTtVN1k
Link to config: https://pastebin.com/7M4yBvVP

**Comment by heidrifx** [comment]
Ok, figured it out. You cannot disable the dust from the gems by blacklisting "dust", you have to blacklist "mekanism" as well. Which is kinda weird as the Mekanism module doesn't add any mekanism recipes for the gem ores.

**Comment by TheLMiffy1111** [comment]
Will fix in next version

**Comment by TheLMiffy1111** [comment]
should be fixed
