### ISSUE TITLE
[1.19.2] Client loading crash with latest KubeJS

### ISSUE THREAD

**Issue by DelviousCrafts** [TheLMiffy1111/JAOPCA#290]
KubeJS updated recently and causes crash with JAOPCA due with no class def found error on startup.

[Crash Report](https://gist.github.com/DelviousCrafts/0254e620bf369d40afc2a05b60dd494b)

[Lates Log](https://gist.github.com/DelviousCrafts/0f857784d401b1125b2545ec5b16acde)

Versions: 
- Minecraft: 1.19.2
- Forge: 43.3.0
- JAOPCA: 4.2.8.18
- KubeJS: 1902.6.2-build 27
- Architectury: 6.5.85
- Rhino: 1902.2.2 - build 280

**Comment by TheLMiffy1111** [comment]
Temporarily downgrade JAOPCA to 4.2.8.17 for now

**Comment by TheLMiffy1111** [comment]
Should be fixed in 4.2.8.19
