### ISSUE TITLE
How to add liquids of certain materials

### ISSUE THREAD

**Issue by SeriousCreeper** [TheLMiffy1111/JAOPCA#291]
Heya,

i'm using the latest 1.12.2 version, and i'm trying to figure out  how to add liquids for some of the metals i have. 

In the old version (before 2.3.x), i was able to add buckets for things like thaumcraft's void and thaumium ingots, but i'm not entirely sure how to do it in the newest version. 

Is there any info on how to set those things up? 

Cheers!

**Comment by TheLMiffy1111** [comment]
You can enable molten fluids for materials by adding to the passiveMaterialWhitelist in the molten module config.
For thaumium and void ingot fluids, you put "Thaumium", "Void" into the whitelist, with the quotes, following the TOML format.

**Comment by SeriousCreeper** [comment]
Sorry for commenting on a closed issue, but i had forgotten how to do this and found my old issue here, and realized i never thanked you for letting me know how to do it lol. So, a very delayed thank you!
