### ISSUE TITLE
[1.16.5] Latest JAOPCA on 1.16.5 Forge crashes on startup with a mixin error.

### ISSUE THREAD

**Issue by Lymia** [TheLMiffy1111/JAOPCA#292]
Forge version: 36.2.41
JAOPCA version: `JAOPCA-1.16.5-3.4.4.27.jar`

[latest.log](https://pastebin.com/gLZv1NhW)
[Crash Report](https://pastebin.com/Wd13UtzV)

This happens even in a modpack without KubeJS, the crash is definitely caused by JAOPCA and apparently JAOPCA alone.

**Comment by TheLMiffy1111** [comment]
Please repost your latest.log
Also try updating to 3.4.4.28 once it is approved

**Comment by Lymia** [comment]
Here you go: [latest.log](https://pastebin.com/J7xrRzSL)

**Comment by Lymia** [comment]
Thank you, 3.4.4.28 seems to fix it.
