### ISSUE TITLE
Crash 1.12.2 NoClassDefFoundError

### ISSUE THREAD

**Issue by ranger135xp** [TheLMiffy1111/JAOPCA#295]
hi,

In a test environment with only 1.12.2, the latest Forge 14.23.5.2860 and these mods:

- JAOPCA 2.3.9.16
- JAOPCAOC 1.0.13
- WrapUp 1.13

The game crashes with this:
java.lang.NoClassDefFoundError: thelm/jaopca/api/ModuleBase

https://pastebin.com/P9ErWEvV

Clocking back a version for both JAOPCA and JAOPCAOC gives the same crash.

**Comment by TheLMiffy1111** [comment]
Currently if you want to use JAOPCAOC on 1.12.2 you need to use JAOPCA 2.2.x
