### ISSUE TITLE
Some config changes not working

### ISSUE THREAD

**Issue by heidrifx** [TheLMiffy1111/JAOPCA#3]
I changed a few settings and it appears to me that everything I did had no effect on the ore processing in an Induction Smelter. I tried editing Ardite which worked, but Platinum didn't. Energy consumption did not increase and when I put Platinum Ore with Cinnabar in the Induction Smelter I get the "original" output (3 Platinum and 1 guaranteed Iridium).

Available recipes for Platinum Ores:
![bildschirmfoto 2017-05-09 um 22 04 31](https://cloud.githubusercontent.com/assets/8414127/25870627/130986c6-3505-11e7-856a-e47248320a21.png)
![bildschirmfoto 2017-05-09 um 22 04 38](https://cloud.githubusercontent.com/assets/8414127/25870630/132e7ba2-3505-11e7-9765-1e2c541c758a.png)

Config for Platinum:
![bildschirmfoto 2017-05-09 um 22 13 40](https://cloud.githubusercontent.com/assets/8414127/25870652/2158de70-3505-11e7-807d-28eff7168063.png)

**Comment by TheLMiffy1111** [comment]
This may be Thermal Expansion's default recipe doing this, I don't know if I can modify this because I'm registering the recipes using IMC here.

**Comment by heidrifx** [comment]
Every other modification works fine just the one for Platinum doesn't work. Maybe you register the recipes later than the others?

**Comment by TheLMiffy1111** [comment]
Um, does any other Thermal Expansion metal work? Such as iridium or aluminum?

**Comment by heidrifx** [comment]
Yes! Aluminum, Iridium, Mithril and all the other ores work just fine. JEI shows the recipes multiple times but the one you add are preferred, only Platinum doesn't seem to work.

**Comment by TheLMiffy1111** [comment]
Oh yea right, I made it so that if you made the extra same as the ore itself, it will instead not produce an extra ingot.

**Comment by heidrifx** [comment]
That's not what I meant. Right now with the current cofig (see top) I have these smelting recipes:
1) 1 Cinnabar + 1 Platinum Ore = 3 Platinum Ingots + 1 Iridium Ingot (4000RF, recipe added by ThermalExpansion) 
2) 1 Cinnabar + 1 Platinum Ore = 3 Platinum Ingots + 75% Rich Slag (8000RF, recipe added by JAOPCA) 
When I try smelting 1 Cinnabar with 1 Platinum Ore I get the top output, not the one I want to get (that would be yours). For all the other ores like Iridium, Mithril or Aluminum I get the outputs that were added by your mod, only Platinum refuses to work.

**Comment by TheLMiffy1111** [comment]
anyways i'll try adding a remove message

**Comment by TheLMiffy1111** [comment]
I've decided that I won't try to fix this because this would be modifying the mod's default recipe, which I decided not to do.
