### ISSUE TITLE
embers rekindled melter recipes output wrong molten fluid (1.20.1)

### ISSUE THREAD

**Issue by Gitcrafter** [TheLMiffy1111/JAOPCA#306]
when melting Create Bigcannons Cast Iron, Steel and Nethersteel in a Melter from Embers Rekindled it will produce Flowing Molten Fluid, which is useless, because the Stamper from Embers Rekindled uses regular Molten Fluid, please change the Melter to produce the regular Molten Fluids

relevant mod versions:
JAOPCA: 1.20.1-4.4.10.15
Embers Rekindled: 1.20.1-1.3.1
Create Bigcannons: 1.20.1-0.5.4

example showing the recipes for Cast Iron Ingots:

![2024-06-23_16 55 19](https://github.com/TheLMiffy1111/JAOPCA/assets/81863925/c10b9365-4902-4238-9be0-d752b44f108f)
![2024-06-23_16 55 25](https://github.com/TheLMiffy1111/JAOPCA/assets/81863925/07156989-7952-4abc-a17d-03cca9bb57de)

**Comment by TheLMiffy1111** [comment]
Should be fixed
