### ISSUE TITLE
[Question] [1.12.2] Integration JAOPCA into the FTB Revelation modpack

### ISSUE THREAD

**Issue by Margatroidu** [TheLMiffy1111/JAOPCA#309]
I play in FTB Revelation modpack and I install JAOPCA and game crashing on startup
One of the options I've been offered is disable the tag chanching for certus quartz, but it didn't work out because I didn't understand how to do it
Сan you tell me how to fix this please?

[crash-2024-07-06_20.52.12-client.txt](https://github.com/user-attachments/files/16170165/crash-2024-07-06_20.52.12-client.txt)

**Comment by TheLMiffy1111** [comment]
Assuming that this is the certus quartz to dust recipe, you need to make sure that it is only added by one source.
To disable JAOPCA adding this recipe, add `"jaopca:ic2.material_to_dust.certus_quartz"` to `recipes.blacklist` in the main JAOPCA config.
To disable JAOPCA adding the alternative oredict entry to certus quartz instead, add `"gemCertusQuartz"` to `oredict.blacklist` in the main JAOPCA config, though I'm not sure that this would work.

**Comment by Margatroidu** [comment]
> Assuming that this is the certus quartz to dust recipe, you need to make sure that it is only added by one source. To disable JAOPCA adding this recipe, add `"jaopca:ic2.material_to_dust.certus_quartz"` to `recipes.blacklist` in the main JAOPCA config.

You're right that solved the problem, but now I'm getting another error with silvering
It looks like this:
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from IndustrialCraft 2 (ic2)
Caused by: ic2.core.util.Config$ParseException: Conflicting recipe at line 43 (OreDict:ingotSilver = thermalfoundation:material@322).`
Everything else is similar to the previous one
I tried adding `"jaopca:ic2.material_to_dust.silver"` to the blacklist, but it had no effect on anything. What am I supposed to do?

**Comment by TheLMiffy1111** [comment]
Another alternative thing you can disable is the IC2 compat module entirely, since it's entirely possible that FTB Revelation has configs/scripts that handles everything
Add `"*"` to the `materialBlacklist` in the `modules/ic2_compat.toml` config file to do that

**Comment by Margatroidu** [comment]
I found another way to fix it. In the ic2 folder in config i opened `metal_former_rolling.ini` file and disable those lines:
`OreDict:ingotSilver = thermalfoundation:material@322`
`OreDict:ingotAluminum = thermalfoundation:material@324`
`OreDict:ingotNickel = thermalfoundation:material@325`
`OreDict:ingotPlatinum = thermalfoundation:material@326`
`OreDict:ingotIridium = thermalfoundation:material@327`
`OreDict:ingotMithril = thermalfoundation:material@328`
`OreDict:ingotElectrum = thermalfoundation:material@353`
`OreDict:ingotInvar = thermalfoundation:material@354`
`OreDict:ingotConstantan = thermalfoundation:material@356`
`OreDict:ingotSignalum = thermalfoundation:material@357`
`OreDict:ingotLumium = thermalfoundation:material@358`
`OreDict:ingotEnderium = thermalfoundation:material@359`

And add tp blacklist those recipes in the main JAOPCA configs:
`"jaopca:ic2.material_to_dust.certus_quartz", "jaopca:ic2.material_to_dust.quartz", "jaopca:ic2.material_to_dust.fluix"`

And now that problem is gone.
