### ISSUE TITLE
[1.12] Crash when exceeding id limit

### ISSUE THREAD

**Issue by TheLimePixel** [TheLMiffy1111/JAOPCA#31]
While Clockwork Phase 2 is a WIP mod, it makes no sense for JAOPCA/WrapUp to crash with it normally, as I have tested the 3 mods together before and everything was fine then:
https://pastebin.com/i
 It seems to have something to do with a fluid.

**Comment by TheLMiffy1111** [comment]
wrong pastebin link?

**Comment by TheLimePixel** [comment]
Woops, here you go: https://pastebin.com/fVeZsfJ2

**Comment by TheLMiffy1111** [comment]
Did you change anything in the config? It seems to be a problem on my side

**Comment by TheLimePixel** [comment]
Nope. And I already figured that it's a problem on your side. :P

**Comment by TheLimePixel** [comment]
Welp, I got the same crash with MagnetiCraft. This is proving to be a real issue.

**Comment by TheLMiffy1111** [comment]
can you put the whole log here?

**Comment by TheLimePixel** [comment]
Log or crash log?

**Comment by TheLMiffy1111** [comment]
The whole minecraft log

**Comment by TheLimePixel** [comment]
https://gist.github.com/EmosewaGamer/de50588b90b46783a0736d999abb5447
It's a mod pack, so it's really long.

**Comment by TheLMiffy1111** [comment]
Here is the problem: your modpack is too big, as too many blocks were registered. Either remove some mods, or get NotEnoughIDs.

**Comment by TheLimePixel** [comment]
Wait then why did it show me that there was an exception with WrapUp instead of that I've ran out of ids?

**Comment by TheLMiffy1111** [comment]
Well, when JAOPCA registers blocks, items, and fluids, when something throws an Exception, it does not crash the game. Therefore, the game progresses into init, and this will happen.

Check here: https://gist.github.com/EmosewaGamer/de50588b90b46783a0736d999abb5447#file-log-L1651

**Comment by TheLimePixel** [comment]
Ok then. Sorry for this.
