### ISSUE TITLE
[1.21] Crash game with latest JAOPCA mod installed

### ISSUE THREAD

**Issue by Periam** [TheLMiffy1111/JAOPCA#311]
After installing the latest version of JAOPCA in a modpack the game crash
The mod and loader version below?

Neoforge 21.0.133
Geockolib-neoforge-1.21-4.5.7
theurgy-1.21-neoforge-1.32.0
Jaopca-1.21-5.0.b.1
jei-1.21-neoforge-19.5.0.59
modonomicon-1.21-neoforge-1.96.1
rhino-2100.2.5-built.44

[debug.log](https://github.com/user-attachments/files/16379141/debug.log)
[latest.log](https://github.com/user-attachments/files/16379143/latest.log)

![image](https://github.com/user-attachments/assets/1bf837f0-ace8-4651-92d9-28180023330f)

**Comment by TheLMiffy1111** [comment]
Should be fixed in 5.0.b.2
