### ISSUE TITLE
Any plans to add a mod to Modrinth?

### ISSUE THREAD

**Issue by Alter73** [TheLMiffy1111/JAOPCA#320]
Hi! I just make quite a lot of modpacks in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if JAOPCA mod was also in Modrinth, otherwise I have to download it separately for each modpack and check for its updates, but this is very inconvenient when creating modpacks. It would be nice if such a cool mod could be downloaded from the second most popular Minecraft modding site.

**Comment by TheLMiffy1111** [comment]
My Modrinth account vanished wtf

Anyways the mods are in fact on Modrinth but Modrinth servers are having problems right now, maybe wait and see if Modrinth fixes itself

**Comment by Alter73** [comment]
Perhaps the reason is different. There is some major outage on Modrinth at the moment, so maybe when the problem is solved, your account will also appear. And yes, thanks for the reply!
