### ISSUE TITLE
Pack Maker Request: Configurable Ex Nihilo

### ISSUE THREAD

**Issue by razage** [TheLMiffy1111/JAOPCA#33]
I'm using Ex Nihilo Creatio, but I assume they all work the same.

I noticed in-game and in the code that all ore pieces are registers with a 20% drop chance from all meshes except the diamond one, which has a 10% chance. I think it would be great if this drop chance was customizable somehow. 

In my case, there are several ores that wouldn't make sense to be such a high chance, and there are probably a couple that should be more common. Or even better would be not just the percentage chance, but what meshes an ore can be gotten from. I know that I can configure via Ex Nihilo extra ore drops, but I don't think I can remove or alter the ones generated by JAOPCA.

Also sidenote: I had to add all the ore chunks generated to the oredictionary myself to get them smelting in tconstruct's smeltery. I'm not sure if that's intentional or not.

**Comment by TheLMiffy1111** [comment]
Will see what I can do.
