### ISSUE TITLE
Crash with latest version of Powered Thingies

### ISSUE THREAD

**Issue by medsal15** [TheLMiffy1111/JAOPCA#37]
https://pastebin.com/Bj2YuWnE

JAOPCA version: 1.12.2-2.2.4.53
WrapUp version: 1.12-1.1.3
Powered Thingies version: 1.12.2-1.0.11-HF
Tesla Core Lib version: 1.12-1.0.11
Forgelin version: 1.5.1
JEI version: 4.8.0.111 (crash also happens without JEI)

**Comment by Staegrin** [comment]
Same
crashlog: https://gist.github.com/Staegrin/2adaec1a834d8ce939e251612433632b
JAOPCA version: 1.12.2 - 2.2.4.53
Powered Thingies 1.12 - 1.0.11 HF

**Comment by faceofcat** [comment]
JAOPCA probably just needs a recompile against my latest version...

sorry for probably breaking this...  I wasn't even aware of this mod :(

also... you should use the [PoweredThingiesAPI ](https://github.com/faceofcat/Tesla-Powered-Thingies/blob/1.12/src/api/kotlin/net/ndrei/teslapoweredthingies/api/PoweredThingiesAPI.kt) to get to the registries and add recipes... a bit "safer" that way... 

contact me on discord about any details/requests.

**Comment by Staegrin** [comment]
Crash has been solved with new version of JAOPCA version JAOPCA-1.12.2-2.2.4.54 
Many thanks to the developers.

**Comment by TheLMiffy1111** [comment]
fixed
