### ISSUE TITLE
[1.12.2] Mekanism crash

### ISSUE THREAD

**Issue by Manuepolis23** [TheLMiffy1111/JAOPCA#38]
https://pastebin.com/AUa8YmJH

**Comment by TheLMiffy1111** [comment]
You are using an unreleased version of Mekanism. The crash is due to that version removing an unobtainable gas to, idk, improve combiner recipes. Since this version is not out yet, I will not fix this issue right now.

**Comment by Manuepolis23** [comment]
now that is released will it be fixed?

**Comment by TheLimePixel** [comment]
It is out now, so you should fix it now :P

**Comment by Endmateria** [comment]
Server Crash

MC 1.12.2
Mekanism 1.12.2-9.4.2.327
Wrapup 1.12-1.1.3
JAOPCA 1.12.2-2.2.5.63

https://gist.github.com/Endmateria/6855d8c3090c224b650176507c2f54f6

**Comment by TheLMiffy1111** [comment]
ok will fix

**Comment by ArMoReDfUrY** [comment]
glad to know it's on the way.

**Comment by TheLMiffy1111** [comment]
fixed
