### ISSUE TITLE
[Question] Exnihilo Creatio

### ISSUE THREAD

**Issue by NielsPilgaard** [TheLMiffy1111/JAOPCA#41]
Hey! I've been trying to disable hunks and pieces from Ex Nihilo Creatio, but with no luck. 
I tried the following, in the blacklist in the config: 
   S:moduleBlacklist <
        exnihilocreatiohunk
        exnihilocreatio hunk
        piece
        hunk
            >

**Comment by TheLMiffy1111** [comment]
S:moduleBlacklist <
exnihilocreatio
\>

**Comment by NielsPilgaard** [comment]
D'oh, I could've sworn I tried that, thanks.
