### ISSUE TITLE
[1.12.2] Error in Server Log (Extreme Reactors conflict)

### ISSUE THREAD

**Issue by Endmateria** [TheLMiffy1111/JAOPCA#44]
I'm getting an error in my server startup log and I've reduced it to a conflict between JAOPCA and Extreme Reactors.  See line 257:  https://gist.github.com/Endmateria/e1ae6316f9ffc7ecd3a89fb1672673c1#file-fml-junk-earlystartup-log

MC 1.12.2
Forge 1.12.2 - 14.23.1.2562
JAOPCA 1.12.2-2.2.5.64
WrapUp 1.12-1.1.3
Zerocore 1.12-0.1.1.0
ExtremeReactors 1.12-0.4.5.44

No other mods installed.
Does not crash server.

**Comment by TheLMiffy1111** [comment]
ok will check

**Comment by TheLMiffy1111** [comment]
question: does JAOPCA work with yellorium in your run?

**Comment by Endmateria** [comment]
I don't see any immediate conflicts with yellorium, but it's an early game.  Seems to work fine with Mekanism's 3x ore processing setup i.e., yellorium clumps become yellorium dirty dust, which becomes yellorium dust, which becomes yellorium ingots.

**Comment by TheLMiffy1111** [comment]
ok then this isn't really an issue, you can ignore that error message
that part was to make yellorium work with JAOPCA
might remove the error generating code

**Comment by Endmateria** [comment]
k
