### ISSUE TITLE
Extra "Block of black quartz" generated.

### ISSUE THREAD

**Issue by u147865** [TheLMiffy1111/JAOPCA#47]
JAOPCA generates an additional "Block of Black Quartz" item when paired with the mod "Actually Additions". I assume this is because the block of black quartz from actually additions isn't tagged with the "blockQuartzBlack" ore dictionary tag.

![image](https://user-images.githubusercontent.com/35321303/34861227-355da966-f718-11e7-9949-0958f7131277.png)
![image](https://user-images.githubusercontent.com/35321303/34861228-3889b648-f718-11e7-90e8-9fcb300847a3.png)

**Comment by ToMe25** [comment]
@u147865 this should be fixed in the newest Actually Additions version.
