### ISSUE TITLE
[Question/Enhancement] Ex-Nihilo Creatio

### ISSUE THREAD

**Issue by accessdenied0** [TheLMiffy1111/JAOPCA#49]
Hey JAOPCA Team,

I would like to know if there is a way to get better control over the compat towards Ex-Nihilo. I like it that all the materials get compatible with other mods, but in Ex-Nihilo it mostly dumps all in the Gravel-meshes. I would like to have more control over that... For example adjust chance, mesh and material (Sand, Gravel...) 

Is it possible to create a JSON, option or add it the actual Ex-Nihilo/SieveRegister.json? It would be great!

**Comment by djwild** [comment]
You can still configure ores by using the sieveregister.json. They get added to the one from JAOPCA.
You can set D:eNCDiamondMultiplier, D:eNCFlintMultiplier and D:eNCIronMultiplier to 0.0 that way you can configures chance/mesh and material with exnihilo json file (JAOPCA will still showing them as 0.0% chance + the one you set in ExNihilo).
I still need to find how to disable them totally from JAOPCA, using blacklist modules "exnihilocreatio", "ore", "piece", doesnt do anything, they keep showing.

**Comment by accessdenied0** [comment]
No they didn't. They get added directly.
I speak of Ex-Nihilo Creatio.
There is only the option to blacklist the module or not. Even the _"D:eNCIronMultiplier"_ options you speak of aren't existing. I can only adjust the _D:rarity_

**Comment by djwild** [comment]
D:eNCIronMultiplier for me are option only on some ores like boron, platinum, uranium, those will get add to the sieves in game by the JAOPCA settings. Iron, gold, etc doesnt have D:eNCIronMultiplier etc and they get added to the sieves by ExNihilo himself. Be sure to set B:enableJSONLoading=true in ExNihiloCreatio.cfg too.

**Comment by accessdenied0** [comment]
Almost.
The configs are almost what I need. Still it just get dumped in "Gravel". You can't adjust that, sadly.
The config is loaded, edited, new created and new edited. JAOPCA doesn't add them to the SieveRegistry.json.

**Comment by TheLMiffy1111** [comment]
Try again now, as I changed how recipes are registered into ENC.
