### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by CJL48** [TheLMiffy1111/JAOPCA#5]
When I attempted to add this mod through multimc, minecraft crashed during startup.
[crash-2017-05-12_11.13.54-client.txt](https://github.com/TheLMiffy1111/JAOPCA/files/997907/crash-2017-05-12_11.13.54-client.txt)

**Comment by TheLMiffy1111** [comment]
Try updating industrialcraft

**Comment by TheLMiffy1111** [comment]
Should be fixed
