### ISSUE TITLE
[bug/Something broke] Mekanism 5x ore processing with ore chunks

### ISSUE THREAD

**Issue by Entayan** [TheLMiffy1111/JAOPCA#50]
Just recently it seems that some ore chunks (added by JAOPCA/AOBD ore chunks) seem not to want to process in Mekanism's dissolution chamber. The ore processing still works for common ore chunks like gold, iron and the like, but it doesn't want to cooperate with draconium, uranium or yellorium chunks.

I'm using versions:
Mekanism 9.4.3.330
JAOPCA-1.12.2-2.2.6.71
JAOPCAOC-1.12.2-1.0.9

I'm not strictly certain if I'm reporting this to the right place as I don't know if JAOPCA adds machine processing support or just the materials (dusts, fluids etc.) but I would appreciate any help that can be offered.

**Comment by TheLMiffy1111** [comment]
DaedalusGame/EmbersRekindled#146

**Comment by TheLMiffy1111** [comment]
fixed in RCXcrafter/AOBDorechunks#13
