### ISSUE TITLE
JAOPCA don't see Purified Crushed Aluminium Ore from Galacticraft

### ISSUE THREAD

**Issue by QuantumStatement** [TheLMiffy1111/JAOPCA#51]
In latest versions of Galacticraft (4.0.1.139+) developers added Crushed Aluminium Ore and Purified Crushed Aluminium Ore. But JAOPCA don't see them and add own crushed ores for Aluminium which cause recipe conflict. Possible reason - different OreDictionary names for Purified Crushed ores in Galacticraft and JAOPCA

Galacticraft
![2018-02-25_11 31 55](https://user-images.githubusercontent.com/35406698/36933278-3e32c5ac-1ee7-11e8-8af2-c632dfe2f670.png)

JAOPCA
![2018-02-25_11 31 36](https://user-images.githubusercontent.com/35406698/36933279-433ef714-1ee7-11e8-91c9-97a96bde9f91.png)

IndustrialCraft 2 (just for reference)
![2018-02-25_11 31 25](https://user-images.githubusercontent.com/35406698/36933275-34b96670-1ee7-11e8-8bbf-7ad6c050d625.png)

Minecraft 1.11.2
Forge 13.20.1.2386
JAOPCA 2.1.6.73
IndustrialCraft 2 2.7.86
Galacticraft 4.0.1.148

**Comment by TheLMiffy1111** [comment]
should be fixed, please check

**Comment by QuantumStatement** [comment]
Yes, it's fixed
