### ISSUE TITLE
[1.12.2] Crash ~ 

### ISSUE THREAD

**Issue by Diamondman121314** [TheLMiffy1111/JAOPCA#53]
I was just launching my test pack after so long, but not sure which mod update broke it. Whether it be your mod or one of the Reborn one's. Still a crash is happening therefore https://pastebin.com/V3zPimzy .

**Comment by trilexcom** [comment]
having the the same issue as well here is the crash log https://pastebin.com/8aPHMpjH

**Comment by modmuss50** [comment]
Looks like I broke the api without realising. I’ll see if I can make it backwards compatible again, if not all you need to do is recompile against the latest TechReborn.
