### ISSUE TITLE
Gem nuggets can't be disabled.

### ISSUE THREAD

**Issue by ManMan36** [TheLMiffy1111/JAOPCA#56]
You can disable nuggets for ingots by going to that ingot's module blacklist and specifying nugget or by disabling them globally. Even with the global blacklist and specifying it in the gems themselves, the gem nuggets won't go away.

**Comment by TheLMiffy1111** [comment]
Can I see the config file?

**Comment by ManMan36** [comment]
Edit: I didn't realize that adding blacklists to an item that already had the global blacklist served as a whitelist instead. I am an idiot.

**Comment by Fortist** [comment]
I dont see how that makes you an idiot when it doesnt say anywhere that blacklisting in both makes the ore specific one a whitelist.

**Comment by TheLMiffy1111** [comment]
sorry for not having docs
