### ISSUE TITLE
Incorrect Fluid Names for Florbs

### ISSUE THREAD

**Issue by cjburkey01** [TheLMiffy1111/JAOPCA#57]
Note: I posted this issue on Thermal Expansion's issue tracker, but was told that it was an issue with this mod, so here we go again:

For example, if I have "Molten meticulum" the florb would show "Molten %s"

An example:

![Florb Naming Issue Example](https://i.imgur.com/7gfKvqt.png)

Here are a bunch of screenshots of the different florbs: https://imgur.com/gallery/s90rD

Here are the actual fluids the florbs are based on: https://imgur.com/gallery/bAg3M

I am in a dev environment, but this occurs in a normal environment as well.

Here are the mods I have and their versions:
- Forge: `1.12.2-14.23.2.2624`
- Thermal Expansion: `1.12.2-5.3.10.15`
- Thermal Foundation: `1.12.2-2.3.10.6`
- CoFH Core: `1.12.2-4.3.10.5`
- JAOPCA: `1.12.2-2.2.6.78`

**Comment by TheLMiffy1111** [comment]
Wouldn't be my problem, because JAOPCA's fluids' localization is all based around two localization entries, one for the fluid type, and one for the ore type.
