### ISSUE TITLE
JAOPCA game crash 

### ISSUE THREAD

**Issue by trilexcom** [TheLMiffy1111/JAOPCA#58]
hi Miffy i am getting a game crash regarding JAOPCA can you please tell me if its Modern Metal or Tech Reborn causing this matter? or if its JAOPCA ?

here is the link to crash log : https://pastebin.com/Ab55zfn5

MC : 1.12.2
Forge : 2635
JAOPCA Version : 2.2.6.78

Thanks again Mat

**Comment by TheLMiffy1111** [comment]
This is actually a duplicate of #31 , try using NotEnoughIDs
