### ISSUE TITLE
The game d'ont launch

### ISSUE THREAD

**Issue by aroxy** [TheLMiffy1111/JAOPCA#6]
The game stop to loading here :
![launch](https://cloud.githubusercontent.com/assets/10050172/26118816/8602020a-3a6b-11e7-871b-b32e8267cdbc.PNG)

**Comment by TheLMiffy1111** [comment]
please put the log here

**Comment by TheLMiffy1111** [comment]
also try the latest version

**Comment by ACGaming** [comment]
Same here, using latest versions in every respect (Forge, IC2, JAOPCA, ...).
My _fml-client-latest.log_: https://paste.ubuntu.com/24591204
Could it be related to AE2 CSV Export?

**Comment by TheLMiffy1111** [comment]
will test with your modpack

**Comment by TheLMiffy1111** [comment]
ok, it got stuck in industrialcraft somehow

**Comment by TheLMiffy1111** [comment]
ok which mods adds vanadium

**Comment by TheLMiffy1111** [comment]
don't know why, but disabling waterpower seems to make loading possible
note: also there was a bug with thermal expansion that i found

**Comment by aroxy** [comment]
water power from wich mod ?

**Comment by ACGaming** [comment]
@aroxy https://minecraft.curseforge.com/projects/water-power

**Comment by ACGaming** [comment]
@TheLMiffy1111 Sounds interesting, good to know!

**Comment by aroxy** [comment]
ohh but in my modpack y d'ont have this mod

**Comment by TheLMiffy1111** [comment]
note that this might be a problem with industrialcraft

**Comment by aroxy** [comment]
And how can i get around this bug ?

**Comment by ACGaming** [comment]
Very odd bug. I hope one is able to find a solution.

**Comment by TheLMiffy1111** [comment]
ic2's replace recipes is not working.
water power's ic2 integration is incorrect.
will be fixed in next version
