### ISSUE TITLE
Ender IO Issue - =Bad file= IMC from other mod

### ISSUE THREAD

**Issue by MokahTGS** [TheLMiffy1111/JAOPCA#62]
https://github.com/SleepyTrousers/EnderIO/issues/4582

I'm getting this as well after updating to the 2.2.6.81 version.

**Comment by tyler489** [comment]
From a quick glance im guessing  you are telling the sagmill to output a stack  of 2 life  crystals but  they dont stack. If so just haave 2 outputs of 1 life crystal each.

**Comment by MokahTGS** [comment]
Rolling back to 2.2.6.78 fixes the issue.

**Comment by TheLMiffy1111** [comment]
see if fixed
