### ISSUE TITLE
New Thermal Update

### ISSUE THREAD

**Issue by Fortist** [TheLMiffy1111/JAOPCA#63]
Breaks Minting for "Wrap Up"

https://pastebin.com/c00w8yTx

**Comment by MokahTGS** [comment]
Yup, confirmed:

https://pastebin.com/RRdKqtiD

Full Mod List: https://pastebin.com/XsQFghxy

Forge 2673
JAOPCA-1.12.2-2.2.6.82.jar
ThermalCultivation-1.12.2-0.2.0.6-universal.jar
ThermalDynamics-1.12.2-2.4.0.8-universal.jar
ThermalExpansion-1.12.2-5.4.0.20-universal.jar
ThermalFoundation-1.12.2-2.4.0.14-universal.jar
ThermalInnovation-1.12.2-0.2.0.4-universal.jar

**Comment by Akitori** [comment]
Hey mine has Press!
https://pastebin.com/AimEBmgQ
still update borked it

**Comment by drakray** [comment]
MINT for me too https://pastebin.com/V49fPjsQ

**Comment by TheLMiffy1111** [comment]
fixed
