### ISSUE TITLE
[Suggestion] IC2 Item Casings and Dense Plates

### ISSUE THREAD

**Issue by TheLordofMelons** [TheLMiffy1111/JAOPCA#65]
IC2 adds item casings which are created by processing plates through some form of metal press again to receive 2 casings.  Example: Iron in a metal press makes an iron plate.  An iron plate in a metal press makes two iron item casings.

IC2 also adds dense plates, which are 9 plates in a compressor to yield 1 dense plate.

Also the config file is a bit of a confusing mess in my opinion.  It's impossible to blacklist an entire mod from being processed as far as I can tell and disabling various parts of the mod such as coins isn't as trivial as it probably could be.

**Comment by TheLMiffy1111** [comment]
will add dense plates
