### ISSUE TITLE
Aluminum vs Aluminium

### ISSUE THREAD

**Issue by trabpukcip** [TheLMiffy1111/JAOPCA#68]
While testing my mod Netherending Ores [(repo)]() with JAOPCA and a bunch of other tech mods, I noticed the funkiness of the oredict entries. I am want to process Nether/End ore in a IC2 macerator. My code only checks for "crushedAluminum", fails to find it and falls back to "dustAluminum".

I looked in JEI and noticed that this mod uses "crushedAluminium" instead. Aluminum should be the correct spelling as the game itself is en_us and other languages are derived from it. I am Australian myself and use en_gb when playing so I expect to see Aluminium but the oredict entires should (ideally) be en_us based. I even try to stick to US english for coding.

 Instead of doing things like this: [CompatNamingNonsense.java](https://github.com/TheLMiffy1111/JAOPCA/blob/1.12/src/main/java/thelm/oredictinit/compat/CompatNamingNonsense.java) why not just register things twice for those specific issues? As far as I can tell that code could have random results because it depends on what other mods are loaded at the time.

To get around it my end I am going to register oredict and search recipe ingredients using both spellings in all situations.

**Comment by TheLMiffy1111** [comment]
Will add a "synonym" system.

**Comment by TheLMiffy1111** [comment]
added
