### ISSUE TITLE
Crash on startup with Tinkers' Construct

### ISSUE THREAD

**Issue by JackyyTV** [TheLMiffy1111/JAOPCA#7]
I am currently using version 1.0.10 of JAOPCA and Forge 12.18.3.2297. Apparently, it's causing startup crash with Tinkers' Construct Smeltery. 
Here's the [crash report](https://pastebin.com/caXQn0F3).

**Comment by TheLMiffy1111** [comment]
ok, will look into it.

**Comment by TheLMiffy1111** [comment]
should be fixed
