### ISSUE TITLE
Crashes when clicking creative tab for JAOPCA in dev environment

### ISSUE THREAD

**Issue by trabpukcip** [TheLMiffy1111/JAOPCA#70]
After adding Thaumcraft and Bables to the build path (#69). I went ahead and clicked the creative tab to see available materials and bam. Crash log: [crash-2018-05-20_00.44.24-client.txt](https://gist.github.com/trabpukcip/9c3b9d6dbcce1e6e380778583baf1eaf)

**Comment by TheLMiffy1111** [comment]
This should be caused by the fact that the mappings used by my deobf jar on curseforge isn't the same as your dev environment.

**Comment by trabpukcip** [comment]
Yeah thanks for pointing that out, I worked around it.
I removed the deobf jaopca jar and wrapup from the build path and used gradle on the normal file instead.

Added these to the dependencies section of build.gradle
```
    compile files ("gradlelibs/JAOPCA-1.12.2-2.2.6.83.jar")
    compile files ("gradlelibs/WrapUp-1.12-1.1.3.jar")
```

This still allows the mod to run with different mappings and no more crashes issue #69 still persists though.
