### ISSUE TITLE
How to add missing nuggets?

### ISSUE THREAD

**Issue by PurpleHel** [TheLMiffy1111/JAOPCA#71]
I don't see nuggets for Mekanism refined obsidian or glowstone. I looked at the config file, but don't understand the syntax or how to add them, cos I'm not very good at this kinda config stuff. JAOPCA 1.10.2-2.0.6.79

**Comment by TheLMiffy1111** [comment]
Go to the "jaopca" section of the config and set "ingot_oreless" to true if you haven't.

**Comment by PurpleHel** [comment]
When I do that, minecraft crashes during start. When I change it back to false, no crash.
Crash https://pastebin.com/6qiu90L5
Config file https://pastebin.com/gfmVvzuv
Full list of mods https://pastebin.com/THwU5Uyw

**Comment by TheLMiffy1111** [comment]
you would have to install NotEnoughIDs

**Comment by PurpleHel** [comment]
Oh, wow, I didn't even notice this pack didn't have it! Thanks, that's fixed it! Glowstone nuggets and no crash!
