### ISSUE TITLE
removal of singularity recipe crash

### ISSUE THREAD

**Issue by TheNimbleNinja** [TheLMiffy1111/JAOPCA#72]
im trying to remove all the singularity recipe to remake them but when i add avaritia to the black list i get a crash. https://gist.github.com/TheNimbleNinja/cb990e41c8c2dc0ed0a02ad19e38295b
and i dont know what to do to stop this crash from happening besides not disabling the recipes for the singularity's

**Comment by TheLMiffy1111** [comment]
Issue is on JAOPCASingularities
