### ISSUE TITLE
Upgrading from 2.2.6.83 to 2.2.7.86 causes minecraft to stall indefinitely in startup

### ISSUE THREAD

**Issue by evhub** [TheLMiffy1111/JAOPCA#73]
Stalls on step 4/7 for FrogCraft: Rebirth, so it seems like an incompatibility with that mod that was introduced with the JAOPCA update.

**Comment by TheLMiffy1111** [comment]
A log might help

**Comment by TheLMiffy1111** [comment]
Seems like an IC2 infinite loop issue I've given up dealing with. Not my problem.

**Comment by TheLMiffy1111** [comment]
Report this to IC2 or FrogCraft
