### ISSUE TITLE
Russian translation.

### ISSUE THREAD

**Issue by jazzyPanikhida** [TheLMiffy1111/JAOPCA#78]
![image](https://user-images.githubusercontent.com/40358088/41665108-661b3410-74d1-11e8-944c-031bc7edc035.png)
 

I am here for this.

**Comment by TheLMiffy1111** [comment]
thank you.
please make sure your translation is consistent with other mods, and please also translate some material names in zh_CN.lang.
if you run into any problems, please tell me.

**Comment by TheLMiffy1111** [comment]
closed due to inactivity
