### ISSUE TITLE
Config questions

### ISSUE THREAD

**Issue by bortooo** [TheLMiffy1111/JAOPCA#8]
1. How can I disable a material?
2. Is possible to disable a dust without disable the nugget?
3. Is possible to add metadata to the second output?

**Comment by TheLMiffy1111** [comment]
1. Haven't added the feature to disable all modules for an ore
2. Yes
3. If you're talking about Ender IO compat, probably

**Comment by bortooo** [comment]
1. Ok thanks, will you do a way to do it?
2. How?
3. I mean that some config are like this:
`#Example`
`S:block=modid:blockname` 
`I:itemMeta=0`
but in JAOPCA config you can't do it.

**Comment by TheLMiffy1111** [comment]
1. Will be in next version.
2. Put "dust" in the module blacklist for that ore
3. Forgot to take that into account, also will do so in the next version, thank you

**Comment by bortooo** [comment]
Ok thanks!
