### ISSUE TITLE
[1.12.2] Alternative for Kinds

### ISSUE THREAD

**Issue by Draskh** [TheLMiffy1111/JAOPCA#80]
I noticed that JAOPCA adds registration for chrome and chromium to let them be the same. There are same kinds that would also profit from this behaviour.
phosphorus | phosphorous
nitre | niter | saltpeter // it is the same material with American or British English name

I would prefer nitre but now I have 6 to 8 different kind of this material in my modpack. I would be great if decide to integrate this the same like you have done for chrome/chromium, sulfur/sulphur etc.

**Comment by TheLMiffy1111** [comment]
phosphorous is a typo
also i did niter
