### ISSUE TITLE
Ae2 integration problem [1.10.2]

### ISSUE THREAD

**Issue by EngineerXL** [TheLMiffy1111/JAOPCA#83]
![image](https://user-images.githubusercontent.com/37447286/42360026-bcd744b4-80ee-11e8-95ed-bd7b3abffd3c.png)
Yep, I tried downgrading version, it helped. I would like to see update with fix or any solution...

**Comment by TheLMiffy1111** [comment]
Current solutions:
1. Set certain orecamouflage entries in AE2's config to false.
2. Add "appliedenergistics" (without quotes) in OreDictInit.cfg's blacklist.
