### ISSUE TITLE
Incompatibility With The Latest GTCE

### ISSUE THREAD

**Issue by TheLimePixel** [TheLMiffy1111/JAOPCA#86]
When installed with the latest GTCE version, all of GTCE's generated recipes break.

**Comment by TheLMiffy1111** [comment]
actually this bug almost feels random, one time i ran a test and recipes were missing, and the next time they were back

**Comment by TheLMiffy1111** [comment]
closing this due to inability to replicate

**Comment by TheLMiffy1111** [comment]
actually looks like the problem's on gregtech
sometimes the part responsible for the recipe isn't called
