### ISSUE TITLE
JAOPCA Crashes with the new beta exnihilocreatio-1.12-0.3.0.jar (1.12.2)

### ISSUE THREAD

**Issue by ghost** [TheLMiffy1111/JAOPCA#87]
Anytime you launch a pack with The new beta and JAOPCA it crashes a pack and won't launch until JAOPCA is disabled or removed.

https://gist.github.com/TacticalUniverse/7d6728b71581a49ea3959bfeead99ba7

**Comment by TheLMiffy1111** [comment]
fixed
