### ISSUE TITLE
Add fluid support

### ISSUE THREAD

**Issue by wizard1399** [TheLMiffy1111/JAOPCA#9]
Could you add molten fluid support for each type of ore the mod finds? I would like to use ember mod to do most of the casting in a pack I am putting together. I have done a lot of looking around. Most mods like this add the item forms but completly ignore the liquid versions.

**Comment by TheLMiffy1111** [comment]
Didn't I already add this? JAOPCA already adds molten versions of ores it finds, and has support for Embers.

**Comment by wizard1399** [comment]
I was going off the description on the curseforge page which does not mention fluids. Sorry if I offended. Will probably be using your mod in a pack named Wizards Gambit. Thanks for all your hard work on the mod!
