### ISSUE TITLE
Piece's not working at all

### ISSUE THREAD

**Issue by ghost** [TheLMiffy1111/JAOPCA#91]
All the following Piece's don't work and we don't know why.

Astral Starmetal Ore Piece
Carbon Ore Piece
Crystal Ore Piece
Dark Iron Ore Piece
Draconium Ore Piece
Iridium Ore Piece
Mercury Ore Piece
Meteoric Iron Ore Piece
Mithril Ore Piece
Palladium Ore Piece
Platinum Ore Piece
Titanium Ore Piece
Tungsten Ore Piece
Yellorium Ore Piece
Zinc Ore Piece

**Comment by remclave** [comment]
Correction: Cannot get from sieving...

**Comment by ThisisCanada98** [comment]
I am also having the same problem. As well as any gems or the such not being added to sieving. I just tested with random supported mods separately, and the ones I've tried have work. Going to test some more to see if I can find out whats going on.

**Comment by ThisisCanada98** [comment]
Alright, after testing the mods that are supported and in the pack I am getting the bug in, in its own separate test pack,  I don't seem to have the issue. My thought is maybe something to do with the mod Just Enough ID's possibly.

**Comment by TheLMiffy1111** [comment]
Is Ex Nihilo's JSON Loading config enabled?

**Comment by remclave** [comment]
We're using ExNihiloCreatio

**Comment by ghost** [comment]
Yes  Ex Nihilo's JSON Loading config enabled.

**Comment by TheLMiffy1111** [comment]
try turning the config off and on again

**Comment by ghost** [comment]
Ok @TheLMiffy1111 I have reset my config and turn back on Ex Nihilo's JSON Loading and still nothing

**Comment by ThisisCanada98** [comment]
Actually turning that config option off seems to fix the problems.

**Comment by TheLMiffy1111** [comment]
next: try deleting the json files
