### ISSUE TITLE
Incompatible with recent API changes to Futurepack

### ISSUE THREAD

**Issue by ubergeek77** [TheLMiffy1111/JAOPCA#92]
Hi! I made an issue about a crash over on the Futurepack issue tracker, and it turns out they recently changed some methods, which is causing JAOPCA to crash.

[https://github.com/mcenderdragon/Futurepack-API/issues/503](https://github.com/mcenderdragon/Futurepack-API/issues/503)

The dev there has already listed out a few things that would need to be changed.

**Comment by TheLMiffy1111** [comment]
fixed
