### ISSUE TITLE
exnihlo crash with jaopca when json is turned on

### ISSUE THREAD

**Issue by TheNimbleNinja** [TheLMiffy1111/JAOPCA#93]
crashes when jsons are enabled with exnihlo and jaopca is installed https://gist.github.com/TheNimbleNinja/afeb6ac90a2f60a28be62e799f6963ab crash log

**Comment by TheLMiffy1111** [comment]
sorry update ex nihilo for now

**Comment by Pival81** [comment]
any update on this?
EDIT: sorry, I also had an old version.
