### ISSUE TITLE
EIO recipe conflict

### ISSUE THREAD

**Issue by TheLimePixel** [TheLMiffy1111/JAOPCA#94]
When using newer EIO versions, with whichever JAOPCA version I use, I get
![image](https://user-images.githubusercontent.com/25333164/47113477-72845e80-d259-11e8-8d4c-f49cd01b407f.png)
when loading up the game

**Comment by VladimirMangos** [comment]
I have similar error for ender dust in 5.0.36 but it fixed for me in EnderIO-1.12.2-5.0.760-nightly.jar (not released yet). You can use 5.0.33 until released next version EnderIO

**Comment by TheLMiffy1111** [comment]
ok will try changing recipe names

**Comment by TheLMiffy1111** [comment]
should be fixed, reopen if issue's still there
