### ISSUE TITLE
Ender IO OreDict compatibility issue

### ISSUE THREAD

**Issue by LumberWizard** [TheLMiffy1111/JAOPCA#96]
Ender IO now adds Ardite and Cobalt dusts, which JAOPCA seems to ignore when adding its own.

**Comment by SashaGelert** [comment]
If you are using CraftTweaker, I would recommend simply adding a script to oredict the dusts.

The other option would be to go to either the JAOPCA config, or the EnderIO user json and disable the dust sources, however this has a higher potential to cause other recipe issues.

**Comment by LumberWizard** [comment]
JAOPCA actually adds its own configs for it (OreDictInit.cfg allows adding oredict entries early), but it would just be better if it was added by default like a lot of other things.
