### ISSUE TITLE
Can't disable exnihilocreatio module

### ISSUE THREAD

**Issue by Pival81** [TheLMiffy1111/JAOPCA#98]
I tried blacklisting the exnihilocreatio module on every material, but the materials keep showing in jei. I know I can just remove the drops from ex nihilo configs, but I want the chunks and pieces to not be registered at all by JAOPCA.
Am I doing something wrong?

**Comment by TheLMiffy1111** [comment]
did you blacklist both global and each module? if so, don't do that

**Comment by Pival81** [comment]
Thanks, that worked.
